import type { ReactNode } from "react";
import {
  ArchiveIcon,
  ArrowClockwiseIcon,
  ArrowUpIcon,
  FolderOpenIcon,
  GitBranchIcon,
  GitCommitIcon,
  HardDrivesIcon,
  HistoryIcon,
  NodesIcon,
  TagIcon,
} from "@/ui/icons";
import type { Command } from "../types/keymaps.types";
import type { GitSidebarAction } from "./git-command-actions";

const gitActions = () => import("./git-command-actions");

function gitSidebarCommand(
  id: string,
  title: string,
  description: string,
  icon: ReactNode,
  action: GitSidebarAction,
  keybindingCommandId?: string,
): Command {
  return {
    id,
    title,
    category: "Git",
    description,
    icon,
    palette: keybindingCommandId ? { keybindingCommandId } : true,
    execute: async () => (await gitActions()).openGitSidebarAction(action),
  };
}

const branches: GitSidebarAction = { type: "manage-branches", tab: "branches" };
const remotes: GitSidebarAction = { type: "manage-remotes" };
const tags: GitSidebarAction = { type: "manage-tags" };
const stashes: GitSidebarAction = { type: "view-stashes" };

export const gitCommands: Command[] = [
  gitSidebarCommand(
    "git.openBranchManager",
    "Git: Open Branch Manager",
    "Open branch manager dropdown",
    <GitBranchIcon />,
    branches,
  ),
  gitSidebarCommand(
    "git.checkoutBranch",
    "Git: Checkout Branch",
    "Open branch manager to switch branches",
    <GitBranchIcon />,
    branches,
  ),
  gitSidebarCommand(
    "git.manageWorktrees",
    "Git: Manage Worktrees",
    "Open the worktree manager",
    <NodesIcon />,
    { type: "manage-branches", tab: "worktrees" },
  ),
  gitSidebarCommand(
    "git.createBranch",
    "Git: Create Branch",
    "Open branch manager and type a new branch name",
    <GitBranchIcon />,
    branches,
  ),
  gitSidebarCommand(
    "git.deleteBranch",
    "Git: Delete Branch",
    "Open branch manager to remove a branch",
    <GitBranchIcon />,
    branches,
  ),
  gitSidebarCommand(
    "git.showBranchDiff",
    "Git: Show Branch Diff",
    "Compare the current branch with another branch",
    <GitBranchIcon />,
    { type: "show-branch-diff" },
  ),
  gitSidebarCommand(
    "git.selectRepository",
    "Git: Select Repository",
    "Browse and select a repository",
    <FolderOpenIcon />,
    { type: "select-repository" },
  ),
  gitSidebarCommand(
    "git.initializeRepository",
    "Git: Initialize Repository",
    "Initialize Git in the current folder",
    <GitBranchIcon />,
    { type: "initialize-repository" },
  ),
  gitSidebarCommand(
    "git.showChanges",
    "Git: Show Changes",
    "Open source control changes",
    <GitBranchIcon />,
    { type: "show-tab", tab: "changes" },
    "workbench.showSourceControl",
  ),
  gitSidebarCommand(
    "git.showHistory",
    "Git: Show History",
    "Open commit history",
    <HistoryIcon />,
    { type: "show-tab", tab: "history" },
  ),
  gitSidebarCommand(
    "git.manageRemotes",
    "Git: Manage Remotes",
    "Open remote manager",
    <HardDrivesIcon />,
    remotes,
  ),
  gitSidebarCommand(
    "git.addRemote",
    "Git: Add Remote",
    "Open remote manager to add a remote",
    <HardDrivesIcon />,
    remotes,
  ),
  gitSidebarCommand(
    "git.removeRemote",
    "Git: Remove Remote",
    "Open remote manager to remove a remote",
    <HardDrivesIcon />,
    remotes,
  ),
  gitSidebarCommand("git.manageTags", "Git: Manage Tags", "Open tag manager", <TagIcon />, tags),
  gitSidebarCommand(
    "git.createTag",
    "Git: Create Tag",
    "Open tag manager to create a tag",
    <TagIcon />,
    tags,
  ),
  gitSidebarCommand(
    "git.deleteTag",
    "Git: Delete Tag",
    "Open tag manager to delete a tag",
    <TagIcon />,
    tags,
  ),
  gitSidebarCommand(
    "git.compareTags",
    "Git: Compare Tags",
    "Open tag manager for tag comparisons",
    <TagIcon />,
    tags,
  ),
  gitSidebarCommand(
    "git.viewStashes",
    "Git: View Stashes",
    "Open stash list",
    <ArchiveIcon />,
    stashes,
  ),
  gitSidebarCommand(
    "git.applyStash",
    "Git: Apply Stash",
    "Open stash list to apply a stash",
    <ArchiveIcon />,
    stashes,
  ),
  gitSidebarCommand(
    "git.popStash",
    "Git: Pop Stash",
    "Open stash list to pop a stash",
    <ArchiveIcon />,
    stashes,
  ),
  gitSidebarCommand(
    "git.dropStash",
    "Git: Drop Stash",
    "Open stash list to drop a stash",
    <ArchiveIcon />,
    stashes,
  ),
  {
    id: "git.stageAll",
    title: "Git: Stage All Changes",
    category: "Git",
    description: "Stage all modified files",
    icon: <GitBranchIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).stageAllChanges(),
  },
  {
    id: "git.unstageAll",
    title: "Git: Unstage All Changes",
    category: "Git",
    description: "Unstage all staged files",
    icon: <GitBranchIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).unstageAllChanges(),
  },
  {
    id: "git.commit",
    title: "Git: Commit Changes",
    category: "Git",
    description: "Commit staged changes",
    icon: <GitCommitIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).commitStagedChanges(),
  },
  {
    id: "git.push",
    title: "Git: Push",
    category: "Git",
    description: "Push changes to remote",
    icon: <ArrowUpIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).pushToRemote(),
  },
  {
    id: "git.pull",
    title: "Git: Pull",
    category: "Git",
    description: "Pull changes from remote",
    icon: <ArrowClockwiseIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).pullFromRemote(),
  },
  {
    id: "git.fetch",
    title: "Git: Fetch",
    category: "Git",
    description: "Fetch changes from remote",
    icon: <ArrowClockwiseIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).fetchFromRemote(),
  },
  {
    id: "git.discardAll",
    title: "Git: Discard All Changes",
    category: "Git",
    description: "Discard all uncommitted changes",
    icon: <GitBranchIcon />,
    palette: { closePalette: "settled" },
    execute: async () => (await gitActions()).discardAllWorkingChanges(),
  },
  {
    id: "git.refresh",
    title: "Git: Refresh Status",
    category: "Git",
    description: "Refresh Git status",
    icon: <ArrowClockwiseIcon />,
    palette: true,
    execute: async () => (await gitActions()).refreshGitStatus(),
  },
];
