import { toast } from "sonner";
import {
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BroomIcon,
  ColumnsIcon,
  CopyIcon,
  RowsIcon,
  SearchIcon,
  SelectAllIcon,
  SparkleIcon,
  TerminalWindowIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@/ui/icons";
import { useZoomStore } from "@/features/window/stores/zoom.store";
import { emitAppEvent } from "@/utils/app-events";
import type { Command } from "../types/keymaps.types";

export const terminalCommands: Command[] = [
  {
    id: "terminal.new",
    title: "New Terminal",
    category: "Terminal",
    description: "Create a new integrated terminal",
    icon: <TerminalWindowIcon />,
    palette: { label: "Terminal: New Terminal" },
    execute: () => emitAppEvent("terminal-new"),
  },
  {
    id: "terminal.close",
    title: "Close Terminal",
    category: "Terminal",
    execute: () => emitAppEvent("close-active-terminal"),
  },
  {
    id: "terminal.find",
    title: "Find in Terminal",
    category: "Terminal",
    description: "Search in the active terminal",
    icon: <SearchIcon />,
    palette: { label: "Terminal: Find" },
    execute: () => emitAppEvent("terminal-open-search"),
  },
  {
    id: "terminal.split",
    title: "Split Terminal Right",
    category: "Terminal",
    description: "Open a terminal beside the active terminal",
    icon: <ColumnsIcon />,
    palette: { label: "Terminal: Split Right" },
    execute: () => emitAppEvent("terminal-split", "right"),
  },
  {
    id: "terminal.splitDown",
    title: "Split Terminal Down",
    category: "Terminal",
    description: "Open a terminal below the active terminal",
    icon: <RowsIcon />,
    palette: { label: "Terminal: Split Down" },
    execute: () => emitAppEvent("terminal-split", "down"),
  },
  {
    id: "terminal.previousCommand",
    title: "Scroll to Previous Command",
    category: "Terminal",
    description: "Jump to the previous prompt in the active terminal",
    icon: <ArrowUpIcon />,
    palette: { label: "Terminal: Scroll to Previous Command" },
    execute: () => emitAppEvent("terminal-navigate-command", "previous"),
  },
  {
    id: "terminal.nextCommand",
    title: "Scroll to Next Command",
    category: "Terminal",
    description: "Jump to the next prompt in the active terminal",
    icon: <ArrowDownIcon />,
    palette: { label: "Terminal: Scroll to Next Command" },
    execute: () => emitAppEvent("terminal-navigate-command", "next"),
  },
  {
    id: "terminal.unsplit",
    title: "Unsplit Terminal",
    category: "Terminal",
    description: "Move the focused terminal pane back into its own tab",
    icon: <TerminalWindowIcon />,
    palette: { label: "Terminal: Unsplit" },
    execute: () => emitAppEvent("terminal-unsplit"),
  },
  {
    id: "terminal.focusNextPane",
    title: "Focus Next Terminal Pane",
    category: "Terminal",
    description: "Move focus to the next split pane of the active terminal",
    icon: <ArrowRightIcon />,
    palette: { label: "Terminal: Focus Next Pane" },
    execute: () => emitAppEvent("terminal-focus-pane", "next"),
  },
  {
    id: "terminal.focusPreviousPane",
    title: "Focus Previous Terminal Pane",
    category: "Terminal",
    description: "Move focus to the previous split pane of the active terminal",
    icon: <ArrowLeftIcon />,
    palette: { label: "Terminal: Focus Previous Pane" },
    execute: () => emitAppEvent("terminal-focus-pane", "previous"),
  },
  {
    id: "terminal.clear",
    title: "Clear Terminal",
    category: "Terminal",
    description: "Clear the scrollback of the active terminal",
    icon: <BroomIcon />,
    palette: { label: "Terminal: Clear" },
    execute: () => emitAppEvent("terminal-clear"),
  },
  {
    id: "terminal.selectAll",
    title: "Select All in Terminal",
    category: "Terminal",
    description: "Select the whole buffer of the active terminal",
    icon: <SelectAllIcon />,
    palette: { label: "Terminal: Select All" },
    execute: () => emitAppEvent("terminal-select-all"),
  },
  {
    id: "terminal.copyLastCommandOutput",
    title: "Copy Last Command Output",
    category: "Terminal",
    description: "Copy the output of the most recent command to the clipboard",
    icon: <CopyIcon />,
    palette: { label: "Terminal: Copy Last Command Output" },
    execute: () => emitAppEvent("terminal-copy-last-command-output"),
  },
  {
    id: "terminal.generateName",
    title: "Terminal: Generate Name",
    category: "Terminal",
    description: "Name the active terminal using your AI connection",
    icon: <SparkleIcon />,
    palette: true,
    execute: async () => {
      const { renameTerminalWithIntelligence } =
        await import("@/features/terminal/services/intelligence-terminal-title");
      toast.promise(renameTerminalWithIntelligence(), {
        loading: "Generating terminal name…",
        success: (applied) =>
          applied ? "Terminal name generated" : "Terminal changed; generated name was not applied",
        error: (error) =>
          error instanceof Error ? error.message : "Could not generate terminal name",
      });
    },
  },
  {
    id: "terminal.zoomIn",
    title: "Terminal: Zoom In",
    category: "Terminal",
    description: "Increase terminal zoom level",
    icon: <ZoomInIcon />,
    palette: true,
    execute: () => useZoomStore.getState().actions.zoomIn("terminal"),
  },
  {
    id: "terminal.zoomOut",
    title: "Terminal: Zoom Out",
    category: "Terminal",
    description: "Decrease terminal zoom level",
    icon: <ZoomOutIcon />,
    palette: true,
    execute: () => useZoomStore.getState().actions.zoomOut("terminal"),
  },
  {
    id: "terminal.resetZoom",
    title: "Terminal: Reset Zoom",
    category: "Terminal",
    description: "Reset terminal zoom to default level",
    icon: <ArrowCounterClockwiseIcon />,
    palette: true,
    execute: () => useZoomStore.getState().actions.resetZoom("terminal"),
  },
];
