import {
  ArrowUpRightIcon,
  BrainIcon,
  BugIcon,
  ChatBubbleTextIcon,
  GitBranchIcon,
  GitPullRequestIcon,
  HardDrivesIcon,
  SearchIcon,
  TerminalWindowIcon,
  UsersIcon,
} from "@/ui/icons";
import type { CoreFeature, CoreFeaturesState } from "../types/feature.types";

export const createCoreFeaturesList = (coreFeatures: CoreFeaturesState): CoreFeature[] => [
  {
    id: "git",
    name: "Git Integration",
    description: "Source control management with Git repositories",
    icon: GitBranchIcon,
    enabled: coreFeatures.git,
  },
  {
    id: "github",
    name: "GitHub Integration",
    description: "Pull requests, issues, and GitHub features",
    icon: GitPullRequestIcon,
    enabled: coreFeatures.github,
  },
  {
    id: "remote",
    name: "Remote Development",
    description: "Connect to remote servers via SSH",
    icon: HardDrivesIcon,
    enabled: coreFeatures.remote,
  },
  {
    id: "terminal",
    name: "Integrated Terminal",
    description: "Built-in terminal for command line operations",
    icon: TerminalWindowIcon,
    enabled: coreFeatures.terminal,
  },
  {
    id: "ghosttyTerminal",
    name: "Ghostty Terminal Engine",
    description: "Use Ghostty's WebAssembly terminal engine for new terminal sessions",
    icon: TerminalWindowIcon,
    enabled: coreFeatures.ghosttyTerminal,
    status: "experimental",
  },
  {
    id: "search",
    name: "Global Search",
    description: "Search across files and folders in workspace",
    icon: SearchIcon,
    enabled: coreFeatures.search,
  },
  {
    id: "diagnostics",
    name: "Diagnostics & Problems",
    description: "Code diagnostics and error reporting",
    icon: BugIcon,
    enabled: coreFeatures.diagnostics,
  },
  {
    id: "debugger",
    name: "Debugger",
    description: "Run and debug files with launch configurations and breakpoints",
    icon: BugIcon,
    enabled: coreFeatures.debugger,
  },
  {
    id: "aiChat",
    name: "Agent",
    description: "Agentic code assistance and workspace tasks",
    icon: ChatBubbleTextIcon,
    enabled: coreFeatures.aiChat,
  },
  {
    id: "teamCollaboration",
    name: "Collaboration",
    description: "Team workspace invites, roles, projects, and channels",
    icon: UsersIcon,
    enabled: coreFeatures.teamCollaboration,
    status: "experimental",
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    description: "File path navigation breadcrumbs in editor",
    icon: ArrowUpRightIcon,
    enabled: coreFeatures.breadcrumbs,
  },
  {
    id: "persistentCommands",
    name: "Persistent Commands",
    description: "The last used commands appear at the top of the command palette",
    icon: BrainIcon,
    enabled: coreFeatures.persistentCommands,
  },
];
