import type { SettingSearchRecord } from "../types/search.types";
import { IS_LINUX, IS_MAC, IS_WINDOWS } from "@/utils/platform";

export const settingsSearchIndex: SettingSearchRecord[] = [
  {
    id: "agent-user-rules",
    tab: "ai-agents",
    section: "Agent instructions",
    label: "User rules",
    description: "Instructions and workspace context exclusions",
    keywords: [
      "rules",
      "instructions",
      "AGENTS.md",
      "CLAUDE.md",
      "ignore",
      "privacy",
      "athasignore",
      "aiignore",
      "cursorignore",
    ],
  },
  {
    id: "cloud-agent-sessions",
    tab: "sharing",
    section: "Cloud Sessions",
    label: "Sync Agent Sessions",
    description: "Read private agent conversations on the web",
    keywords: ["cloud", "sync", "private", "sessions", "web"],
  },
  {
    id: "shared-links",
    tab: "sharing",
    section: "Shared Items",
    label: "Shared Items",
    description: "Manage shared links, visibility, and live updates",
    keywords: ["share", "public", "live", "visibility", "revoke"],
  },
  // Enterprise Settings
  {
    id: "enterprise-managed-mode",
    tab: "enterprise",
    section: "Enterprise Controls",
    label: "Managed Mode",
    description: "Enforce enterprise policy controls in the desktop app",
    keywords: ["enterprise", "managed", "policy", "organization", "admin"],
  },
  {
    id: "enterprise-extension-allowlist-toggle",
    tab: "enterprise",
    section: "Enterprise Controls",
    label: "Require Integration Allowlist",
    description: "Only approved integration IDs can be installed or updated",
    keywords: ["enterprise", "integrations", "extensions", "allowlist", "policy", "security"],
  },
  {
    id: "enterprise-allow-byok",
    tab: "enterprise",
    section: "Enterprise Controls",
    label: "Allow BYOK Autocomplete",
    description: "Allow user-provided OpenRouter keys for autocomplete",
    keywords: ["enterprise", "byok", "openrouter", "autocomplete", "api", "key"],
  },
  {
    id: "enterprise-ai-completion",
    tab: "enterprise",
    section: "Enterprise Controls",
    label: "Enable AI Autocomplete",
    description: "Enable inline AI completion for enterprise users",
    keywords: ["enterprise", "ai", "autocomplete", "completion"],
  },
  {
    id: "enterprise-ai-chat",
    tab: "enterprise",
    section: "Enterprise Controls",
    label: "Enable Agent",
    description: "Enable Agent panel for enterprise users",
    keywords: ["enterprise", "ai", "agent", "chat", "panel"],
  },
  {
    id: "enterprise-extension-allowlist-entries",
    tab: "enterprise",
    section: "Integration Allowlist",
    label: "Integration Allowlist",
    description: "Approved integration IDs for enterprise-managed environments",
    keywords: ["enterprise", "integrations", "extensions", "ids", "allowlist", "approved"],
  },

  // Editor Settings
  {
    id: "editor-auto-save",
    tab: "editor",
    section: "Tabs and Files",
    label: "Auto Save",
    description: "Automatically save files when editing",
    keywords: ["save", "automatic", "files"],
  },
  {
    id: "editor-font-family",
    tab: "editor",
    section: "Font",
    label: "Font Family",
    description: "Font family for code editor",
    keywords: ["font", "editor", "code", "typography", "family", "monospace"],
  },
  {
    id: "editor-font-size",
    tab: "editor",
    section: "Font",
    label: "Font Size",
    description: "Editor font size in pixels",
    keywords: ["font", "size", "editor", "typography"],
  },
  {
    id: "editor-font-ligatures",
    tab: "editor",
    section: "Font",
    label: "Font Ligatures",
    description: "Use programming ligatures provided by the selected editor font",
    keywords: ["font", "ligatures", "symbols", "typography", "code"],
  },
  {
    id: "editor-italic-comments",
    tab: "editor",
    section: "Font",
    label: "Italic Comments",
    description: "Render code comments in italics",
    keywords: ["comments", "italic", "font", "style", "syntax", "code"],
  },
  {
    id: "editor-line-height",
    tab: "editor",
    section: "Font",
    label: "Line Height",
    description: "Editor line height multiplier",
    keywords: ["line", "height", "spacing", "editor", "typography"],
  },
  {
    id: "editor-tab-size",
    tab: "editor",
    section: "Tabs and Files",
    label: "Tab Size",
    description: "Number of spaces per tab",
    keywords: ["tab", "size", "indentation", "spaces"],
  },
  {
    id: "editor-word-wrap",
    tab: "editor",
    section: "Display",
    label: "Word Wrap",
    description: "Wrap lines that exceed viewport width",
    keywords: ["word", "wrap", "lines", "display"],
  },
  {
    id: "editor-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Line Numbers",
    description: "Show line numbers in the editor",
    keywords: ["line", "numbers", "gutter", "display"],
  },
  {
    id: "editor-render-whitespace",
    tab: "editor",
    section: "Display",
    label: "Render Whitespace",
    description: "Show visible markers for spaces and tabs",
    keywords: ["whitespace", "spaces", "tabs", "invisible", "render", "display"],
  },
  {
    id: "editor-render-indent-guides",
    tab: "editor",
    section: "Display",
    label: "Indent Guides",
    description: "Show vertical guides for indentation levels",
    keywords: ["indent", "guides", "indentation", "tabs", "spaces", "display"],
  },
  {
    id: "editor-highlight-occurrences",
    tab: "editor",
    section: "Display",
    label: "Highlight Occurrences",
    description: "Highlight visible matches for the word under the cursor",
    keywords: ["highlight", "occurrences", "matches", "word", "symbol", "cursor"],
  },
  {
    id: "editor-show-minimap",
    tab: "editor",
    section: "Display",
    label: "Show Minimap",
    description: "Show a minimap overview of the code on the right side of the editor",
    keywords: ["minimap", "overview", "code", "preview", "display"],
  },
  {
    id: "editor-show-outline",
    tab: "editor",
    section: "Display",
    label: "Show Outline",
    description: "Show symbols beside each editor tab",
    keywords: ["outline", "symbols", "panel", "structure", "display"],
  },
  {
    id: "editor-sticky-scroll",
    tab: "editor",
    section: "Display",
    label: "Sticky Scroll",
    description: "Keep containing scopes visible at the top while scrolling",
    keywords: ["sticky", "scroll", "scope", "function", "class", "header"],
  },
  {
    id: "editor-bracket-pair-colorization",
    tab: "editor",
    section: "Display",
    label: "Bracket Pair Colorization",
    description: "Use matching colors to distinguish nested bracket pairs",
    keywords: ["bracket", "pair", "color", "parentheses", "nested", "rainbow"],
  },
  {
    id: "editor-smooth-scrolling",
    tab: "editor",
    section: "Cursor and Scrolling",
    label: "Smooth Scrolling",
    description: "Animate editor scrolling between positions",
    keywords: ["smooth", "scroll", "animation", "editor"],
  },
  {
    id: "editor-scroll-beyond-last-line",
    tab: "editor",
    section: "Cursor and Scrolling",
    label: "Scroll Beyond Last Line",
    description: "Allow scrolling the final line above the bottom of the editor",
    keywords: ["scroll", "last", "line", "bottom", "padding"],
  },
  {
    id: "editor-cursor-style",
    tab: "editor",
    section: "Cursor and Scrolling",
    label: "Cursor Style",
    description: "Shape of the editor cursor outside Vim normal mode",
    keywords: ["cursor", "caret", "style", "line", "block", "underline"],
  },
  {
    id: "editor-cursor-blinking",
    tab: "editor",
    section: "Cursor and Scrolling",
    label: "Cursor Blinking",
    description: "Animation used by the editor cursor outside Vim normal mode",
    keywords: ["cursor", "caret", "blink", "animation", "solid"],
  },
  {
    id: "editor-relative-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Relative Line Numbers",
    description: "Show relative numbers when Vim mode is active",
    keywords: ["line", "numbers", "relative", "vim"],
  },
  {
    id: "editor-vim-mode",
    tab: "keyboard",
    section: "Keyboard",
    label: "Vim Mode",
    description: "Enable vim keybindings and commands",
    keywords: ["vim", "keybindings", "modal", "editing"],
  },
  {
    id: "editor-max-open-tabs",
    tab: "editor",
    section: "Tabs and Files",
    label: "Max Open Tabs",
    description: "Maximum number of tabs before oldest closes",
    keywords: ["tabs", "limit", "maximum", "open"],
  },

  // File Tree Settings
  {
    id: "file-tree-sort-order",
    tab: "file-explorer",
    section: "Display",
    label: "Sort Order",
    description: "Choose whether folders stay above files or everything sorts by name",
    keywords: ["sort", "order", "folders", "files", "name", "alphabetical"],
  },
  {
    id: "file-tree-indent-size",
    tab: "file-explorer",
    section: "Display",
    label: "Indent Size",
    description: "Pixels per nesting level in the file tree",
    keywords: ["indent", "indentation", "nesting", "depth", "tree", "file explorer", "spacing"],
  },
  {
    id: "file-tree-show-file-icons",
    tab: "file-explorer",
    section: "Display",
    label: "Show File Icons",
    description: "Show themed file and folder icons",
    keywords: ["file", "folder", "icon", "theme", "display"],
  },
  {
    id: "file-tree-show-folder-arrows",
    tab: "file-explorer",
    section: "Display",
    label: "Show Folder Arrows",
    description: "Show expand and collapse arrows beside folders",
    keywords: ["folder", "arrow", "chevron", "expand", "collapse", "disclosure", "tree"],
  },
  {
    id: "file-tree-show-indent-guides",
    tab: "file-explorer",
    section: "Display",
    label: "Show Indent Guides",
    description: "Show vertical guides for nested folders",
    keywords: ["indent", "guide", "tree", "nested", "folder", "line"],
  },
  {
    id: "file-tree-show-hidden-files",
    tab: "file-explorer",
    section: "Display",
    label: "Show Hidden Files",
    description: "Show dotfiles and hidden directories in the file tree",
    keywords: ["hidden", "dotfiles", "dotfile", "files", "folders", "directories", "visibility"],
  },
  {
    id: "file-tree-compact-folders",
    tab: "file-explorer",
    section: "Display",
    label: "Compact Folders",
    description: "Collapse single-child folder chains in the file tree",
    keywords: ["compact", "folders", "directories", "single child", "collapse", "nested"],
  },
  {
    id: "file-tree-hide-root-folder",
    tab: "file-explorer",
    section: "Display",
    label: "Hide Root Folder",
    description: "Show project files directly at the top level",
    keywords: ["root", "folder", "project", "workspace", "top level", "file explorer"],
  },
  {
    id: "file-tree-respect-gitignore",
    tab: "file-explorer",
    section: "Display",
    label: "Respect .gitignore",
    description: "Hide files matched by root and nested .gitignore files",
    keywords: ["gitignore", ".gitignore", "ignored", "git", "files", "visibility", "exclude"],
  },
  {
    id: "file-tree-show-git-status",
    tab: "file-explorer",
    section: "Display",
    label: "Show Git Status",
    description: "Display Git color decorations beside changed files",
    keywords: ["git", "file tree", "files", "decorations", "status", "color"],
  },
  {
    id: "file-tree-auto-reveal-active-file",
    tab: "file-explorer",
    section: "Behavior",
    label: "Auto Reveal Active File",
    description: "Expand and scroll Files to the active editor file",
    keywords: ["auto", "reveal", "active", "file", "scroll", "expand", "editor"],
  },
  {
    id: "file-tree-confirm-before-delete",
    tab: "file-explorer",
    section: "Behavior",
    label: "Confirm Before Delete",
    description: "Ask for confirmation before deleting a file or folder",
    keywords: ["confirm", "delete", "file", "folder", "safety", "warning"],
  },
  {
    id: "file-tree-hidden-file-patterns",
    tab: "file-explorer",
    section: "Filters",
    label: "Hidden Files",
    description: "Files matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "files", "patterns", "glob", "filter", "exclude"],
  },
  {
    id: "file-tree-hidden-directory-patterns",
    tab: "file-explorer",
    section: "Filters",
    label: "Hidden Directories",
    description: "Directories matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "directories", "folders", "patterns", "glob", "filter", "exclude"],
  },
  {
    id: "github-token-source",
    tab: "git",
    section: "GitHub Account",
    label: "Token Source",
    description: "Choose between a personal access token, your Athas account, or the GitHub CLI",
    keywords: ["github", "token", "auth", "credential", "source", "gh", "cli", "organization"],
  },
  {
    id: "github-personal-access-token",
    tab: "git",
    section: "GitHub Account",
    label: "Personal Access Token",
    description: "Use your own GitHub token when an organization has not approved Athas",
    keywords: ["github", "pat", "token", "personal access token", "org", "sso", "ghp"],
  },
  {
    id: "github-cli-token",
    tab: "git",
    section: "GitHub Account",
    label: "GitHub CLI",
    description: "Reuse the token from your gh CLI installation",
    keywords: ["github", "gh", "cli", "token", "reuse", "terminal"],
  },
  {
    id: "git-folder-based-changes",
    tab: "git",
    section: "Git View",
    label: "Folder-Based Changes",
    description: "Show Git changes in a folder tree, similar to Files",
    keywords: ["git", "changes", "folder", "tree", "files", "explorer", "sidebar"],
  },
  {
    id: "git-confirm-before-discard",
    tab: "git",
    section: "Integration",
    label: "Confirm Before Discard",
    description: "Show a confirmation before discarding Git changes",
    keywords: ["git", "discard", "confirm", "danger", "revert"],
  },
  {
    id: "git-auto-refresh-status",
    tab: "git",
    section: "Integration",
    label: "Auto Refresh Git Status",
    description: "Refresh Git status automatically after relevant file and Git events",
    keywords: ["git", "refresh", "auto", "status", "save"],
  },
  {
    id: "git-show-untracked-files",
    tab: "git",
    section: "Git View",
    label: "Show Untracked Files",
    description: "Display untracked files in the Git view",
    keywords: ["git", "untracked", "files", "status"],
  },
  {
    id: "git-show-staged-first",
    tab: "git",
    section: "Git View",
    label: "Show Staged First",
    description: "Render staged changes before unstaged changes",
    keywords: ["git", "staged", "order", "changes"],
  },
  {
    id: "git-default-diff-view",
    tab: "git",
    section: "Git View",
    label: "Default Diff View",
    description: "Choose unified or split as the default diff layout",
    keywords: ["git", "diff", "split", "unified", "layout"],
  },
  {
    id: "git-open-diff-on-click",
    tab: "git",
    section: "Git View",
    label: "Open Diff On Click",
    description: "Open a diff directly when clicking a changed file",
    keywords: ["git", "diff", "click", "open", "file"],
  },
  {
    id: "git-compact-status-badges",
    tab: "git",
    section: "Git View",
    label: "Compact Git Status Badges",
    description: "Use denser diff stats and staged indicators in the Git panel",
    keywords: ["git", "compact", "badges", "status", "dense"],
  },
  {
    id: "git-collapse-empty-sections",
    tab: "git",
    section: "Git View",
    label: "Collapse Empty Sections",
    description: "Hide empty sections in the Git panel",
    keywords: ["git", "collapse", "empty", "sections", "staged"],
  },
  {
    id: "git-remember-last-panel-mode",
    tab: "git",
    section: "Git View",
    label: "Remember Last Git Panel Mode",
    description: "Restore the last open stash or history panel section",
    keywords: ["git", "remember", "panel", "stash", "history"],
  },
  {
    id: "git-enable-inline-blame",
    tab: "git",
    section: "Editor",
    label: "Enable Inline Blame",
    description: "Show inline Git blame metadata in the editor",
    keywords: ["git", "blame", "inline", "editor"],
  },

  // Appearance Settings
  {
    id: "appearance-theme",
    tab: "appearance",
    section: "Theme",
    label: "Color Theme",
    description: "Choose your preferred color theme",
    keywords: ["theme", "color", "appearance", "dark", "light"],
  },
  {
    id: "appearance-sync-system-theme",
    tab: "appearance",
    section: "Theme",
    label: "Sync With OS",
    description:
      "Follow the operating system appearance and switch light or dark themes automatically",
    keywords: ["theme", "system", "os", "auto", "light", "dark", "appearance", "sync"],
  },
  {
    id: "appearance-auto-theme-light",
    tab: "appearance",
    section: "Theme",
    label: "Preferred Light Theme",
    description: "Theme to use while the operating system is in light appearance",
    keywords: ["theme", "light", "system", "os", "auto", "appearance"],
  },
  {
    id: "appearance-auto-theme-dark",
    tab: "appearance",
    section: "Theme",
    label: "Preferred Dark Theme",
    description: "Theme to use while the operating system is in dark appearance",
    keywords: ["theme", "dark", "system", "os", "auto", "appearance"],
  },
  {
    id: "appearance-icon-theme",
    tab: "appearance",
    section: "Theme",
    label: "Icons",
    description: "Icons displayed in the file tree and tabs",
    keywords: ["icon", "theme", "file", "tree", "tabs"],
  },
  {
    id: "appearance-custom-themes",
    tab: "appearance",
    section: "Theme",
    label: "Custom Themes",
    description: "Create, import, and remove custom Athas theme JSON files",
    keywords: ["custom", "theme", "json", "create", "generator", "import", "upload"],
  },
  {
    id: "appearance-ui-font",
    tab: "appearance",
    section: "Typography",
    label: "UI Font Family",
    description: "Font family for UI elements (file tree, markdown, etc.)",
    keywords: ["font", "ui", "typography", "family"],
  },
  {
    id: "appearance-ui-font-size",
    tab: "appearance",
    section: "Typography",
    label: "UI Font Size",
    description: "Adjust UI text and icon scale in 0.5px steps",
    keywords: ["font", "size", "ui", "icon", "scale", "typography"],
  },
  {
    id: "appearance-reduce-motion",
    tab: "appearance",
    section: "Interface",
    label: "Reduce Motion",
    description: "Reduce non-essential interface animations while keeping state changes visible",
    keywords: ["motion", "animation", "accessibility", "reduce", "interface"],
  },
  {
    id: "appearance-show-tab-icons",
    tab: "appearance",
    section: "Interface",
    label: "Show Tab Icons",
    description: "Show file and view icons in editor tabs",
    keywords: ["tab", "icon", "file", "view", "interface", "hide"],
  },
  {
    id: "appearance-ui-density",
    tab: "appearance",
    section: "Interface",
    label: "UI Density",
    description: "Space around tabs, toolbars, and workspace panes",
    keywords: ["window", "chrome", "density", "compact", "comfortable", "spacing", "layout"],
  },
  {
    id: "appearance-tab-close-buttons",
    tab: "appearance",
    section: "Interface",
    label: "Tab Close Buttons",
    description: "Choose when unpinned tabs show their close button",
    keywords: ["tab", "close", "button", "active", "hover", "always"],
  },
  ...(!IS_MAC && !IS_WINDOWS && !IS_LINUX
    ? [
        {
          id: "appearance-native-menu-bar",
          tab: "appearance",
          section: "Layout",
          label: "Native Menu Bar",
          description: "Use the native menu bar or a custom UI menu bar",
          keywords: ["menu", "bar", "native", "ui"],
        } satisfies SettingSearchRecord,
      ]
    : []),
  ...(!IS_MAC
    ? [
        {
          id: "appearance-compact-menu-bar",
          tab: "appearance",
          section: "Layout",
          label: "Compact Menu Bar",
          description: "Requires UI menu bar; compact hamburger or full UI menu",
          keywords: ["menu", "bar", "compact", "hamburger", "ui"],
        } satisfies SettingSearchRecord,
      ]
    : []),
  {
    id: "appearance-window-transparency",
    tab: "appearance",
    section: "Layout",
    label: "Window Transparency",
    description: "Use translucent app chrome and transparent native windows where supported",
    keywords: ["window", "transparency", "transparent", "translucent", "glass", "chrome"],
  },
  {
    id: "appearance-open-folders-new-window",
    tab: "appearance",
    section: "Layout",
    label: "Open Projects In New Window",
    description:
      "Open each new project in a separate window and disable activity-bar project switching",
    keywords: ["open", "folder", "project", "new", "window", "separate", "activity", "switch"],
  },

  // AI Settings
  {
    id: "ai-athas-plan",
    tab: "ai",
    section: "Athas",
    label: "Plan",
    description: "Your plan and the monthly credit it includes for Athas models",
    keywords: ["ai", "athas", "pro", "plan", "billing", "subscription", "intelligence"],
  },
  {
    id: "ai-athas-credit",
    tab: "ai",
    section: "Athas",
    label: "Included credit",
    description: "How much of this month's included Athas credit is left",
    keywords: ["ai", "credit", "usage", "allowance", "limit", "quota"],
  },
  {
    id: "ai-athas-balance",
    tab: "ai",
    section: "Athas",
    label: "Balance",
    description: "Prepaid balance used after included credit runs out",
    keywords: ["ai", "wallet", "balance", "top up", "add credit", "prepaid", "billing"],
  },
  {
    id: "ai-default-model",
    tab: "ai",
    section: "Default model",
    label: "Default model",
    description: "The model new chats, inline edits, and other AI features use",
    keywords: ["ai", "provider", "model", "llm", "default", "chat", "agent", "athas", "automatic"],
  },
  {
    id: "ai-feature-models",
    tab: "ai",
    section: "Other features",
    label: "Models per feature",
    description: "Use a different model for commit messages, titles, reviews, and other features",
    keywords: ["ai", "model", "override", "commit", "title", "review", "inline edit", "github"],
  },
  {
    id: "ai-provider-key-anthropic",
    tab: "ai-models",
    section: "API keys",
    label: "Anthropic API key",
    description: "Use Anthropic models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "claude"],
  },
  {
    id: "ai-provider-key-openai",
    tab: "ai-models",
    section: "API keys",
    label: "OpenAI API key",
    description: "Use OpenAI models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "gpt"],
  },
  {
    id: "ai-provider-key-gemini",
    tab: "ai-models",
    section: "API keys",
    label: "Google Gemini API key",
    description: "Use Google Gemini models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "google"],
  },
  {
    id: "ai-provider-key-grok",
    tab: "ai-models",
    section: "API keys",
    label: "xAI Grok API key",
    description: "Use xAI Grok models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "xai"],
  },
  {
    id: "ai-provider-key-deepseek",
    tab: "ai-models",
    section: "API keys",
    label: "DeepSeek API key",
    description: "Use DeepSeek models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "deepseek"],
  },
  {
    id: "ai-provider-key-mistral",
    tab: "ai-models",
    section: "API keys",
    label: "Mistral AI API key",
    description: "Use Mistral AI models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "mistral"],
  },
  {
    id: "ai-provider-key-qwen",
    tab: "ai-models",
    section: "API keys",
    label: "Qwen API key",
    description: "Use Qwen models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "qwen"],
  },
  {
    id: "ai-provider-key-openrouter",
    tab: "ai-models",
    section: "API keys",
    label: "OpenRouter API key",
    description: "Use OpenRouter models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "openrouter"],
  },
  {
    id: "ai-provider-key-vercel",
    tab: "ai-models",
    section: "API keys",
    label: "Vercel AI Gateway API key",
    description: "Use Vercel AI Gateway models with your own API key",
    keywords: ["ai", "api", "key", "byok", "provider", "vercel"],
  },
  {
    id: "ai-ollama-endpoint",
    tab: "ai-models",
    section: "Ollama",
    label: "Server address",
    description: "Where your Ollama server runs, on this machine or on Ollama Cloud",
    keywords: ["ollama", "endpoint", "url", "local", "lan", "cloud", "host", "port", "offline"],
  },
  {
    id: "ai-ollama-api-key",
    tab: "ai-models",
    section: "Ollama",
    label: "API key",
    description: "Key for Ollama Cloud or a protected Ollama server",
    keywords: ["ollama", "api", "key", "token", "auth", "cloud", "bearer"],
  },
  {
    id: "ai-custom-provider",
    tab: "ai-models",
    section: "Custom endpoint",
    label: "Server address",
    description: "Connect any OpenAI-compatible server such as LM Studio or vLLM",
    keywords: [
      "ai",
      "custom",
      "provider",
      "endpoint",
      "base",
      "url",
      "openai compatible",
      "lm studio",
      "vllm",
      "local",
    ],
  },
  {
    id: "ai-autocomplete",
    tab: "ai-completion",
    section: "Suggestions",
    label: "Tab completion",
    description: "Suggest code as you type and accept it with Tab",
    keywords: ["ai", "autocomplete", "completion", "inline", "tab", "suggestions", "copilot"],
  },
  {
    id: "ai-autocomplete-model",
    tab: "ai-completion",
    section: "Suggestions",
    label: "Model",
    description: "The model Tab completion uses, separate from the default model",
    keywords: ["ai", "model", "autocomplete", "completion", "tab", "local", "automatic"],
  },
  {
    id: "ai-agents",
    tab: "ai-agents",
    section: "Agents",
    label: "Agents",
    description: "Install Codex, Claude Agent, Gemini CLI, and other coding agents",
    keywords: ["ai", "agent", "acp", "codex", "claude", "gemini", "install", "cli"],
  },
  {
    id: "ai-agent-notifications",
    tab: "notifications",
    section: "Activity",
    label: "Agent Notifications",
    description: "Show native notifications when background agent work needs attention",
    keywords: ["ai", "agent", "notification", "native", "system", "background", "permission"],
  },
  {
    id: "ai-agent-finish-notifications",
    tab: "notifications",
    section: "Activity",
    label: "Agent Finished Notifications",
    description: "Also notify when an agent turn finishes or fails",
    keywords: ["ai", "agent", "notification", "finished", "complete", "error", "done"],
  },
  {
    id: "ai-agent-notification-sound",
    tab: "notifications",
    section: "Activity",
    label: "Agent Notification Sound",
    description: "Play the system sound with agent notifications",
    keywords: ["ai", "agent", "notification", "sound", "audio", "alert"],
  },
  {
    id: "ai-agent-max-steps",
    tab: "ai-agents",
    section: "Agent behavior",
    label: "Steps before pausing",
    description: "Model requests one Athas agent turn may make before it pauses",
    keywords: ["ai", "agent", "steps", "budget", "limit", "tool", "calls", "continue"],
  },
  {
    id: "ai-follow-agent",
    tab: "ai-agents",
    section: "Agent behavior",
    label: "Follow Agent",
    description: "Start new agent chats with the editor following the files the agent works in",
    keywords: ["ai", "agent", "follow", "acp", "editor", "location"],
  },
  {
    id: "ai-allowed-commands",
    tab: "ai-agents",
    section: "Allowed Commands",
    label: "Allowed Commands",
    description: "Commands and MCP tools the Athas agent runs without asking",
    keywords: ["ai", "agent", "allow", "always", "command", "permission", "approve", "mcp", "tool"],
  },
  {
    id: "ai-clear-chats",
    tab: "ai-agents",
    section: "Chat history",
    label: "Clear chat history",
    description: "Permanently delete every agent chat",
    keywords: ["ai", "agent", "chat", "clear", "delete", "history"],
  },
  {
    id: "ai-mcp-servers",
    tab: "ai-mcp",
    section: "MCP Servers",
    label: "MCP Servers",
    description: "Configure MCP servers used by agents",
    keywords: [
      "mcp",
      "server",
      "servers",
      "tools",
      "context",
      "agent",
      "acp",
      "stdio",
      "http",
      "sse",
    ],
  },

  // Keyboard Settings
  {
    id: "keyboard-quick-file-open",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Quick File Open",
    description: "Open file picker",
    keywords: ["keyboard", "shortcut", "file", "open", "picker"],
  },
  {
    id: "keyboard-save-file",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Save File",
    description: "Save current file",
    keywords: ["keyboard", "shortcut", "save", "file"],
  },
  {
    id: "keyboard-new-file",
    tab: "keyboard",
    section: "Shortcuts",
    label: "New File",
    description: "Create new file",
    keywords: ["keyboard", "shortcut", "new", "file", "create"],
  },
  {
    id: "keyboard-close-tab",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Close Tab",
    description: "Close current tab",
    keywords: ["keyboard", "shortcut", "close", "tab"],
  },
  {
    id: "keyboard-command-palette",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Command Palette",
    description: "Open command palette",
    keywords: ["keyboard", "shortcut", "command", "palette"],
  },
  {
    id: "keyboard-toggle-sidebar",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Toggle Sidebar",
    description: "Show/hide the sidebar",
    keywords: ["keyboard", "shortcut", "sidebar", "toggle"],
  },
  {
    id: "keyboard-next-tab",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Next Tab",
    description: "Switch to next tab",
    keywords: ["keyboard", "shortcut", "tab", "next", "switch"],
  },
  {
    id: "keyboard-find",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Find",
    description: "Search in current file",
    keywords: ["keyboard", "shortcut", "find", "search"],
  },
  {
    id: "keyboard-find-replace",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Find & Replace",
    description: "Find and replace text",
    keywords: ["keyboard", "shortcut", "find", "replace", "search"],
  },
  {
    id: "keyboard-comment-line",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Comment Line",
    description: "Toggle line comment",
    keywords: ["keyboard", "shortcut", "comment", "toggle"],
  },
  {
    id: "keyboard-duplicate-line",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Duplicate Line",
    description: "Duplicate current line",
    keywords: ["keyboard", "shortcut", "duplicate", "line", "copy"],
  },
  {
    id: "keyboard-toggle-terminal",
    tab: "keyboard",
    section: "Shortcuts",
    label: "Toggle Terminal",
    description: "Show/hide integrated terminal",
    keywords: ["keyboard", "shortcut", "terminal", "toggle"],
  },
  {
    id: "keyboard-new-terminal",
    tab: "keyboard",
    section: "Shortcuts",
    label: "New Terminal",
    description: "Create new terminal instance",
    keywords: ["keyboard", "shortcut", "terminal", "new", "create"],
  },

  // Language Settings
  {
    id: "language-default-language",
    tab: "editor",
    section: "Tabs and Files",
    label: "Default Language",
    description: "Default syntax highlighting for new files",
    keywords: ["language", "syntax", "highlighting", "default"],
  },
  {
    id: "language-auto-detect",
    tab: "editor",
    section: "Tabs and Files",
    label: "Auto-detect Language",
    description: "Automatically detect file language from integration",
    keywords: ["language", "auto", "detect", "extension"],
  },
  {
    id: "language-format-on-save",
    tab: "editor",
    section: "Language Features",
    label: "Format on Save",
    description: "Automatically format code when saving",
    keywords: ["format", "save", "automatic", "formatting", "prettier"],
  },
  {
    id: "language-lint-on-save",
    tab: "editor",
    section: "Language Features",
    label: "Lint on Save",
    description: "Run linter when saving files",
    keywords: ["lint", "linter", "save", "eslint", "check"],
  },
  {
    id: "language-auto-completion",
    tab: "editor",
    section: "Language Features",
    label: "Auto Completion",
    description: "Show completion suggestions while typing",
    keywords: ["autocomplete", "completion", "intellisense", "suggestions"],
  },
  {
    id: "language-parameter-hints",
    tab: "editor",
    section: "Language Features",
    label: "Parameter Hints",
    description: "Show function parameter hints",
    keywords: ["parameter", "hints", "intellisense", "function"],
  },
  {
    id: "language-inlay-hints",
    tab: "editor",
    section: "Language Features",
    label: "Inlay Hints",
    description: "Show inline type and parameter hints from language servers",
    keywords: ["inlay", "hints", "types", "parameters", "lsp"],
  },
  {
    id: "language-code-lens",
    tab: "editor",
    section: "Language Features",
    label: "Code Lens",
    description: "Show inline code actions above symbols",
    keywords: ["code", "lens", "actions", "lsp"],
  },
  {
    id: "language-semantic-tokens",
    tab: "editor",
    section: "Language Features",
    label: "Semantic Tokens",
    description: "Use language server semantic highlighting",
    keywords: ["semantic", "tokens", "highlighting", "lsp"],
  },

  // Features Settings
  {
    id: "features-git",
    tab: "git",
    section: "Integration",
    label: "Git Integration",
    description: "Source control management with Git repositories",
    keywords: ["git", "source", "control", "version"],
  },
  {
    id: "github-action-notifications",
    tab: "notifications",
    section: "Activity",
    label: "Workflow Run Notifications",
    description: "Workflow updates for your runs and pull requests",
    keywords: ["github", "actions", "workflow", "ci", "notifications", "toast", "native"],
  },
  // Terminal Settings
  {
    id: "terminal-default-shell",
    tab: "terminal",
    section: "Launch",
    label: "Default Shell",
    description: "Fallback shell when a terminal profile does not override it",
    keywords: ["terminal", "shell", "default", "bash", "zsh", "fish"],
  },
  {
    id: "terminal-default-profile",
    tab: "terminal",
    section: "Launch",
    label: "Default Profile",
    description: "Used by the terminal toolbar button and Cmd+T when the terminal is focused",
    keywords: ["terminal", "profile", "default", "launch"],
  },
  {
    id: "terminal-shell-integration",
    tab: "terminal",
    section: "Launch",
    label: "Shell Integration",
    description:
      "Track commands, exit codes, and the working directory in zsh, bash, fish, PowerShell, and Git Bash",
    keywords: ["terminal", "shell", "integration", "prompt", "command", "marks", "osc 133"],
  },
  {
    id: "terminal-minimum-contrast",
    tab: "terminal",
    section: "Typography",
    label: "Minimum Contrast",
    description: "Adjust ANSI colors that would be hard to read against the terminal background",
    keywords: ["terminal", "contrast", "ansi", "colors", "legibility", "accessibility"],
  },
  {
    id: "terminal-command-notifications",
    tab: "notifications",
    section: "Activity",
    label: "Command Notifications",
    description: "Notify when a long command finishes in a terminal you are not looking at",
    keywords: ["terminal", "notification", "command", "finished", "toast", "background"],
  },
  {
    id: "terminal-font-family",
    tab: "terminal",
    section: "Typography",
    label: "Font Family",
    description: "Font family for the integrated terminal",
    keywords: ["terminal", "font", "family", "monospace", "nerd font"],
  },
  {
    id: "terminal-font-size",
    tab: "terminal",
    section: "Typography",
    label: "Font Size",
    description: "Terminal font size in pixels",
    keywords: ["terminal", "font", "size"],
  },
  {
    id: "terminal-line-height",
    tab: "terminal",
    section: "Typography",
    label: "Line Height",
    description: "Line height multiplier for terminal",
    keywords: ["terminal", "line", "height", "spacing"],
  },
  {
    id: "terminal-letter-spacing",
    tab: "terminal",
    section: "Typography",
    label: "Letter Spacing",
    description: "Additional spacing between characters in terminal",
    keywords: ["terminal", "letter", "spacing", "characters"],
  },
  {
    id: "terminal-scrollback",
    tab: "terminal",
    section: "Typography",
    label: "Scrollback",
    description: "How many terminal history lines to retain",
    keywords: ["terminal", "scrollback", "history", "buffer", "lines"],
  },
  {
    id: "terminal-alt-click-moves-cursor",
    tab: "terminal",
    section: "Interaction",
    label: "Alt Click Moves Cursor",
    description: "Move the shell prompt cursor to the clicked position when supported",
    keywords: ["terminal", "alt", "click", "cursor", "prompt", "mouse"],
  },
  {
    id: "terminal-option-as-meta",
    tab: "terminal",
    section: "Interaction",
    label: "Option as Meta",
    description: "Treat the Option key as Meta in terminal applications on macOS",
    keywords: ["terminal", "option", "meta", "alt", "mac", "macos", "keyboard"],
  },
  {
    id: "terminal-right-click-selects-word",
    tab: "terminal",
    section: "Interaction",
    label: "Right Click Selects Word",
    description: "Select the word under the pointer before opening the context menu",
    keywords: ["terminal", "right", "click", "select", "word", "context", "menu"],
  },
  {
    id: "terminal-cursor-style",
    tab: "terminal",
    section: "Cursor",
    label: "Cursor Style",
    description: "Shape of the terminal cursor",
    keywords: ["terminal", "cursor", "style", "block", "underline", "bar"],
  },
  {
    id: "terminal-cursor-blink",
    tab: "terminal",
    section: "Cursor",
    label: "Blinking Cursor",
    description: "Whether the terminal cursor should blink",
    keywords: ["terminal", "cursor", "blink", "blinking"],
  },
  {
    id: "terminal-cursor-width",
    tab: "terminal",
    section: "Cursor",
    label: "Cursor Width",
    description: "Thickness of the terminal cursor",
    keywords: ["terminal", "cursor", "width", "thickness", "bar"],
  },
  {
    id: "terminal-cursor-inactive-style",
    tab: "terminal",
    section: "Cursor",
    label: "Inactive Cursor Style",
    description: "Appearance of the terminal cursor when the terminal is not focused",
    keywords: ["terminal", "cursor", "inactive", "unfocused", "outline", "hidden"],
  },

  {
    id: "editor-horizontal-tab-scroll",
    tab: "editor",
    section: "Tabs and Files",
    label: "Buffer Carousel",
    description: "Show open buffers as a horizontally scrollable carousel in the main view",
    keywords: ["tabs", "buffers", "carousel", "scroll", "horizontal", "trackpad", "main view"],
  },
  // Advanced Settings
  {
    id: "advanced-export-settings",
    tab: "advanced",
    section: "Data",
    label: "Export Settings",
    description: "Save all app settings to a JSON file",
    keywords: ["export", "settings", "backup", "json", "sync"],
  },
  {
    id: "advanced-import-settings",
    tab: "advanced",
    section: "Data",
    label: "Import Settings",
    description: "Restore app settings from a JSON file",
    keywords: ["import", "settings", "restore", "backup", "json"],
  },
  {
    id: "general-import-editor-settings",
    tab: "general",
    section: "Application",
    label: "Import From Another Editor",
    description: "Import matching setup from another editor",
    keywords: [
      "import",
      "settings",
      "keybindings",
      "projects",
      "recent",
      "vscode",
      "cursor",
      "windsurf",
      "zed",
      "jetbrains",
    ],
  },
  {
    id: "advanced-reset-settings",
    tab: "advanced",
    section: "Reset",
    label: "Reset Settings",
    description: "Reset all settings to defaults",
    keywords: ["reset", "settings", "defaults", "restore"],
  },
  {
    id: "advanced-telemetry",
    tab: "advanced",
    section: "Telemetry",
    label: "Anonymous Usage Telemetry",
    description:
      "Send anonymous operational metadata for updates, heartbeats, integrations, and crashes",
    keywords: [
      "telemetry",
      "analytics",
      "tracking",
      "privacy",
      "crash",
      "updates",
      "integrations",
      "extensions",
    ],
  },
];
