import type { SettingSearchRecord } from "../types/search";

export const settingsSearchIndex: SettingSearchRecord[] = [
  // General Settings
  {
    id: "editor-auto-save",
    tab: "editor",
    section: "Saving",
    label: "Auto Save",
    description: "Automatically save files when editing",
    keywords: ["save", "automatic", "files"],
  },
  {
    id: "general-command-bar-file-limit",
    tab: "general",
    section: "File Management",
    label: "Command Bar File Limit",
    description: "Maximum files to index for quick file search. Increase for large monorepos.",
    keywords: [
      "command",
      "bar",
      "file",
      "limit",
      "search",
      "quick",
      "open",
      "monorepo",
      "index",
      "cmd p",
    ],
  },
  {
    id: "editor-mouse-wheel-zoom",
    tab: "editor",
    section: "Display",
    label: "Mouse Wheel Zoom",
    description: "Use Ctrl+Scroll to zoom editor",
    keywords: ["zoom", "mouse", "wheel", "scroll", "ctrl"],
  },
  {
    id: "general-open-settings",
    tab: "general",
    section: "Quick Access",
    label: "Open Settings",
    description: "Keyboard shortcut to open settings",
    keywords: ["keyboard", "shortcut", "settings"],
  },
  {
    id: "general-toggle-sidebar",
    tab: "general",
    section: "Quick Access",
    label: "Toggle Sidebar",
    description: "Show or hide the sidebar",
    keywords: ["keyboard", "shortcut", "sidebar", "toggle"],
  },
  {
    id: "general-zoom-in",
    tab: "general",
    section: "Quick Access",
    label: "Zoom In",
    description: "Increase zoom level",
    keywords: ["keyboard", "shortcut", "zoom", "increase"],
  },
  {
    id: "general-zoom-out",
    tab: "general",
    section: "Quick Access",
    label: "Zoom Out",
    description: "Decrease zoom level",
    keywords: ["keyboard", "shortcut", "zoom", "decrease"],
  },
  {
    id: "general-reset-zoom",
    tab: "general",
    section: "Quick Access",
    label: "Reset Zoom",
    description: "Reset zoom to 100%",
    keywords: ["keyboard", "shortcut", "zoom", "reset"],
  },

  // Editor Settings
  {
    id: "editor-font-family",
    tab: "editor",
    section: "Typography",
    label: "Editor Font Family",
    description: "Font family for code editor",
    keywords: ["font", "editor", "code", "typography", "family", "monospace"],
  },
  {
    id: "editor-font-size",
    tab: "editor",
    section: "Typography",
    label: "Font Size",
    description: "Editor font size in pixels",
    keywords: ["font", "size", "editor", "typography"],
  },
  {
    id: "editor-tab-size",
    tab: "editor",
    section: "Typography",
    label: "Tab Size",
    description: "Number of spaces per tab",
    keywords: ["tab", "size", "indentation", "spaces"],
  },
  {
    id: "editor-word-wrap",
    tab: "editor",
    section: "Display",
    label: "Word Wrap",
    description: "Wrap lines that exceed viewport width",
    keywords: ["word", "wrap", "lines", "display"],
  },
  {
    id: "editor-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Line Numbers",
    description: "Show line numbers in the editor",
    keywords: ["line", "numbers", "gutter", "display"],
  },
  {
    id: "editor-show-minimap",
    tab: "editor",
    section: "Display",
    label: "Show Minimap",
    description: "Show a minimap overview of the code on the right side of the editor",
    keywords: ["minimap", "overview", "code", "preview", "display"],
  },
  {
    id: "editor-relative-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Relative Line Numbers",
    description: "Show relative numbers when Vim mode is active",
    keywords: ["line", "numbers", "relative", "vim"],
  },
  {
    id: "editor-vim-mode",
    tab: "editor",
    section: "Input",
    label: "Vim Mode",
    description: "Enable vim keybindings and commands",
    keywords: ["vim", "keybindings", "modal", "editing"],
  },
  {
    id: "editor-max-open-tabs",
    tab: "editor",
    section: "Tabs",
    label: "Max Open Tabs",
    description: "Maximum number of tabs before oldest closes",
    keywords: ["tabs", "limit", "maximum", "open"],
  },

  // General Settings (non-editor)
  {
    id: "general-command-bar-preview",
    tab: "general",
    section: "Command Bar",
    label: "Command Bar Preview",
    description: "Show file preview in command bar",
    keywords: ["command", "bar", "preview", "file", "quick open"],
  },

  // File Tree Settings
  {
    id: "file-tree-hidden-file-patterns",
    tab: "fileTree",
    section: "File Tree Settings",
    label: "Hidden File Patterns",
    description: "Files matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "files", "patterns", "glob", "filter", "exclude"],
  },
  {
    id: "file-tree-hidden-directory-patterns",
    tab: "fileTree",
    section: "File Tree Settings",
    label: "Hidden Directory Patterns",
    description: "Directories matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "directories", "folders", "patterns", "glob", "filter", "exclude"],
  },

  // Appearance Settings
  {
    id: "appearance-theme",
    tab: "appearance",
    section: "Theme",
    label: "Color Theme",
    description: "Choose your preferred color theme",
    keywords: ["theme", "color", "appearance", "dark", "light"],
  },
  {
    id: "appearance-icon-theme",
    tab: "appearance",
    section: "Theme",
    label: "Icon Theme",
    description: "Icons displayed in the file tree and tabs",
    keywords: ["icon", "theme", "file", "tree", "tabs"],
  },
  {
    id: "appearance-ui-font",
    tab: "appearance",
    section: "Typography",
    label: "UI Font Family",
    description: "Font family for UI elements (file tree, markdown, etc.)",
    keywords: ["font", "ui", "typography", "family"],
  },
  {
    id: "appearance-sidebar-position",
    tab: "appearance",
    section: "Layout",
    label: "Sidebar Position",
    description: "Choose where to position the sidebar",
    keywords: ["sidebar", "position", "left", "right", "layout"],
  },
  {
    id: "appearance-native-menu-bar",
    tab: "appearance",
    section: "Layout",
    label: "Native Menu Bar",
    description: "Use the native menu bar or a custom UI menu bar",
    keywords: ["menu", "bar", "native", "ui"],
  },
  {
    id: "appearance-compact-menu-bar",
    tab: "appearance",
    section: "Layout",
    label: "Compact Menu Bar",
    description: "Requires UI menu bar; compact hamburger or full UI menu",
    keywords: ["menu", "bar", "compact", "hamburger", "ui"],
  },

  // AI Settings
  {
    id: "ai-provider",
    tab: "ai",
    section: "Provider & Model",
    label: "Provider",
    description: "Choose your AI service provider",
    keywords: ["ai", "provider", "llm", "service"],
  },
  {
    id: "ai-model",
    tab: "ai",
    section: "Provider & Model",
    label: "Model",
    description: "Select the AI model to use",
    keywords: ["ai", "model", "llm"],
  },
  {
    id: "ai-api-keys",
    tab: "ai",
    section: "API Keys",
    label: "API Keys",
    description: "Configure API keys for AI providers",
    keywords: ["api", "key", "authentication", "credentials"],
  },
  {
    id: "ai-auto-open-files",
    tab: "ai",
    section: "Behavior",
    label: "Auto Open Read Files",
    description: "Automatically open files in the editor when AI reads them",
    keywords: ["ai", "auto", "open", "read", "files", "editor"],
  },
  {
    id: "ai-autocomplete",
    tab: "ai",
    section: "Autocomplete",
    label: "AI Completion",
    description: "Enable AI autocomplete in the editor",
    keywords: ["ai", "autocomplete", "completion", "openrouter"],
  },
  {
    id: "ai-autocomplete-model",
    tab: "ai",
    section: "Autocomplete",
    label: "Autocomplete Model",
    description: "Choose the OpenRouter model used for autocomplete",
    keywords: ["ai", "model", "autocomplete", "openrouter"],
  },
  {
    id: "ai-autocomplete-byok",
    tab: "ai",
    section: "Autocomplete",
    label: "Autocomplete BYOK",
    description: "Use your own OpenRouter API key for autocomplete on the free plan",
    keywords: ["ai", "autocomplete", "byok", "openrouter", "api key", "free"],
  },

  // Keyboard Settings
  {
    id: "keyboard-quick-file-open",
    tab: "keyboard",
    section: "File Operations",
    label: "Quick File Open",
    description: "Open file picker",
    keywords: ["keyboard", "shortcut", "file", "open", "picker"],
  },
  {
    id: "keyboard-save-file",
    tab: "keyboard",
    section: "File Operations",
    label: "Save File",
    description: "Save current file",
    keywords: ["keyboard", "shortcut", "save", "file"],
  },
  {
    id: "keyboard-new-file",
    tab: "keyboard",
    section: "File Operations",
    label: "New File",
    description: "Create new file",
    keywords: ["keyboard", "shortcut", "new", "file", "create"],
  },
  {
    id: "keyboard-close-tab",
    tab: "keyboard",
    section: "File Operations",
    label: "Close Tab",
    description: "Close current tab",
    keywords: ["keyboard", "shortcut", "close", "tab"],
  },
  {
    id: "keyboard-command-palette",
    tab: "keyboard",
    section: "Navigation",
    label: "Command Palette",
    description: "Open command palette",
    keywords: ["keyboard", "shortcut", "command", "palette"],
  },
  {
    id: "keyboard-toggle-sidebar",
    tab: "keyboard",
    section: "Navigation",
    label: "Toggle Sidebar",
    description: "Show/hide sidebar",
    keywords: ["keyboard", "shortcut", "sidebar", "toggle"],
  },
  {
    id: "keyboard-go-to-line",
    tab: "keyboard",
    section: "Navigation",
    label: "Go to Line",
    description: "Jump to specific line",
    keywords: ["keyboard", "shortcut", "go", "line", "jump", "navigate"],
  },
  {
    id: "keyboard-next-tab",
    tab: "keyboard",
    section: "Navigation",
    label: "Next Tab",
    description: "Switch to next tab",
    keywords: ["keyboard", "shortcut", "tab", "next", "switch"],
  },
  {
    id: "keyboard-find",
    tab: "keyboard",
    section: "Editor",
    label: "Find",
    description: "Search in current file",
    keywords: ["keyboard", "shortcut", "find", "search"],
  },
  {
    id: "keyboard-find-replace",
    tab: "keyboard",
    section: "Editor",
    label: "Find & Replace",
    description: "Find and replace text",
    keywords: ["keyboard", "shortcut", "find", "replace", "search"],
  },
  {
    id: "keyboard-comment-line",
    tab: "keyboard",
    section: "Editor",
    label: "Comment Line",
    description: "Toggle line comment",
    keywords: ["keyboard", "shortcut", "comment", "toggle"],
  },
  {
    id: "keyboard-duplicate-line",
    tab: "keyboard",
    section: "Editor",
    label: "Duplicate Line",
    description: "Duplicate current line",
    keywords: ["keyboard", "shortcut", "duplicate", "line", "copy"],
  },
  {
    id: "keyboard-toggle-terminal",
    tab: "keyboard",
    section: "Terminal",
    label: "Toggle Terminal",
    description: "Show/hide integrated terminal",
    keywords: ["keyboard", "shortcut", "terminal", "toggle"],
  },
  {
    id: "keyboard-new-terminal",
    tab: "keyboard",
    section: "Terminal",
    label: "New Terminal",
    description: "Create new terminal instance",
    keywords: ["keyboard", "shortcut", "terminal", "new", "create"],
  },

  // Language Settings
  {
    id: "language-default-language",
    tab: "language",
    section: "Language Support",
    label: "Default Language",
    description: "Default syntax highlighting for new files",
    keywords: ["language", "syntax", "highlighting", "default"],
  },
  {
    id: "language-auto-detect",
    tab: "language",
    section: "Language Support",
    label: "Auto-detect Language",
    description: "Automatically detect file language from extension",
    keywords: ["language", "auto", "detect", "extension"],
  },
  {
    id: "language-format-on-save",
    tab: "language",
    section: "Code Formatting",
    label: "Format on Save",
    description: "Automatically format code when saving",
    keywords: ["format", "save", "automatic", "formatting", "prettier"],
  },
  {
    id: "language-lint-on-save",
    tab: "language",
    section: "Code Formatting",
    label: "Lint on Save",
    description: "Run linter when saving files",
    keywords: ["lint", "linter", "save", "eslint", "check"],
  },
  {
    id: "language-formatter",
    tab: "language",
    section: "Code Formatting",
    label: "Default Formatter",
    description: "Choose default code formatter",
    keywords: ["format", "formatter", "prettier", "eslint"],
  },
  {
    id: "language-auto-completion",
    tab: "language",
    section: "IntelliSense",
    label: "Auto Completion",
    description: "Show completion suggestions while typing",
    keywords: ["autocomplete", "completion", "intellisense", "suggestions"],
  },
  {
    id: "language-parameter-hints",
    tab: "language",
    section: "IntelliSense",
    label: "Parameter Hints",
    description: "Show function parameter hints",
    keywords: ["parameter", "hints", "intellisense", "function"],
  },

  // Features Settings
  {
    id: "features-git",
    tab: "features",
    section: "Features",
    label: "Git Integration",
    description: "Source control management with Git repositories",
    keywords: ["git", "source", "control", "version"],
  },
  {
    id: "features-remote",
    tab: "features",
    section: "Features",
    label: "Remote Development",
    description: "Connect to remote servers via SSH",
    keywords: ["remote", "ssh", "server", "development"],
  },
  {
    id: "features-terminal",
    tab: "features",
    section: "Features",
    label: "Integrated Terminal",
    description: "Built-in terminal for command line operations",
    keywords: ["terminal", "command", "line", "shell"],
  },
  {
    id: "features-search",
    tab: "features",
    section: "Features",
    label: "Global Search",
    description: "Search across files and folders in workspace",
    keywords: ["search", "find", "global", "workspace"],
  },
  {
    id: "features-diagnostics",
    tab: "features",
    section: "Features",
    label: "Diagnostics & Problems",
    description: "Code diagnostics and error reporting",
    keywords: ["diagnostics", "problems", "errors", "linting"],
  },
  {
    id: "features-ai-chat",
    tab: "features",
    section: "Features",
    label: "AI Assistant",
    description: "AI-powered code assistance and chat",
    keywords: ["ai", "assistant", "chat"],
  },
  {
    id: "features-breadcrumbs",
    tab: "features",
    section: "Features",
    label: "Breadcrumbs",
    description: "File path navigation breadcrumbs in editor",
    keywords: ["breadcrumbs", "navigation", "path"],
  },

  // Terminal Settings
  {
    id: "terminal-font-family",
    tab: "terminal",
    section: "Typography",
    label: "Terminal Font Family",
    description: "Font family for the integrated terminal",
    keywords: ["terminal", "font", "family", "monospace", "nerd font"],
  },
  {
    id: "terminal-font-size",
    tab: "terminal",
    section: "Typography",
    label: "Terminal Font Size",
    description: "Terminal font size in pixels",
    keywords: ["terminal", "font", "size"],
  },
  {
    id: "terminal-line-height",
    tab: "terminal",
    section: "Typography",
    label: "Terminal Line Height",
    description: "Line height multiplier for terminal",
    keywords: ["terminal", "line", "height", "spacing"],
  },
  {
    id: "terminal-letter-spacing",
    tab: "terminal",
    section: "Typography",
    label: "Terminal Letter Spacing",
    description: "Additional spacing between characters in terminal",
    keywords: ["terminal", "letter", "spacing", "characters"],
  },
  {
    id: "terminal-cursor-style",
    tab: "terminal",
    section: "Cursor",
    label: "Terminal Cursor Style",
    description: "Shape of the terminal cursor",
    keywords: ["terminal", "cursor", "style", "block", "underline", "bar"],
  },
  {
    id: "terminal-cursor-blink",
    tab: "terminal",
    section: "Cursor",
    label: "Terminal Cursor Blink",
    description: "Whether the terminal cursor should blink",
    keywords: ["terminal", "cursor", "blink", "blinking"],
  },

  // Extensions Settings
  {
    id: "extensions-browse",
    tab: "extensions",
    section: "Extensions",
    label: "Browse Extensions",
    description: "Browse and manage installed extensions",
    keywords: ["extensions", "browse", "install", "manage", "language", "theme", "icon"],
  },

  // Advanced Settings
  {
    id: "advanced-reset-settings",
    tab: "advanced",
    section: "Data",
    label: "Reset Settings",
    description: "Reset all settings to defaults",
    keywords: ["reset", "settings", "defaults", "restore"],
  },
];
