import type { SettingSearchRecord } from "../types/search";

export const settingsSearchIndex: SettingSearchRecord[] = [
  // General Settings
  {
    id: "general-auto-save",
    tab: "general",
    section: "File Management",
    label: "Auto Save",
    description: "Automatically save files when editing",
    keywords: ["save", "automatic", "files"],
  },
  {
    id: "general-sidebar-position",
    tab: "general",
    section: "Layout",
    label: "Sidebar Position",
    description: "Choose where to position the sidebar",
    keywords: ["sidebar", "position", "layout", "left", "right"],
  },
  {
    id: "general-mouse-wheel-zoom",
    tab: "general",
    section: "Zoom",
    label: "Mouse Wheel Zoom",
    description: "Use mouse wheel to zoom in/out",
    keywords: ["zoom", "mouse", "wheel", "scroll"],
  },
  {
    id: "general-open-settings",
    tab: "general",
    section: "Quick Access",
    label: "Open Settings",
    description: "Keyboard shortcut to open settings",
    keywords: ["keyboard", "shortcut", "settings"],
  },
  {
    id: "general-toggle-sidebar",
    tab: "general",
    section: "Quick Access",
    label: "Toggle Sidebar",
    description: "Show or hide the sidebar",
    keywords: ["keyboard", "shortcut", "sidebar", "toggle"],
  },
  {
    id: "general-zoom-in",
    tab: "general",
    section: "Quick Access",
    label: "Zoom In",
    description: "Increase zoom level",
    keywords: ["keyboard", "shortcut", "zoom", "increase"],
  },
  {
    id: "general-zoom-out",
    tab: "general",
    section: "Quick Access",
    label: "Zoom Out",
    description: "Decrease zoom level",
    keywords: ["keyboard", "shortcut", "zoom", "decrease"],
  },
  {
    id: "general-reset-zoom",
    tab: "general",
    section: "Quick Access",
    label: "Reset Zoom",
    description: "Reset zoom to 100%",
    keywords: ["keyboard", "shortcut", "zoom", "reset"],
  },

  // Editor Settings
  {
    id: "editor-ui-font-family",
    tab: "editor",
    section: "Typography",
    label: "UI Font Family",
    description: "Font family for UI elements (file tree, markdown, etc.)",
    keywords: ["font", "ui", "typography", "family"],
  },
  {
    id: "editor-font-family",
    tab: "editor",
    section: "Typography",
    label: "Editor Font Family",
    description: "Font family for code editor",
    keywords: ["font", "editor", "code", "typography", "family", "monospace"],
  },
  {
    id: "editor-font-size",
    tab: "editor",
    section: "Typography",
    label: "Font Size",
    description: "Editor font size in pixels",
    keywords: ["font", "size", "editor", "typography"],
  },
  {
    id: "editor-tab-size",
    tab: "editor",
    section: "Typography",
    label: "Tab Size",
    description: "Number of spaces per tab",
    keywords: ["tab", "size", "indentation", "spaces"],
  },
  {
    id: "editor-word-wrap",
    tab: "editor",
    section: "Display",
    label: "Word Wrap",
    description: "Wrap lines that exceed viewport width",
    keywords: ["word", "wrap", "lines", "display"],
  },
  {
    id: "editor-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Line Numbers",
    description: "Show line numbers in the editor",
    keywords: ["line", "numbers", "gutter", "display"],
  },
  {
    id: "editor-relative-line-numbers",
    tab: "editor",
    section: "Display",
    label: "Relative Line Numbers",
    description: "Show relative numbers when Vim mode is active",
    keywords: ["line", "numbers", "relative", "vim"],
  },
  {
    id: "editor-vim-mode",
    tab: "editor",
    section: "Input",
    label: "Vim Mode",
    description: "Enable vim keybindings and commands",
    keywords: ["vim", "keybindings", "modal", "editing"],
  },

  // File Tree Settings
  {
    id: "file-tree-hidden-file-patterns",
    tab: "fileTree",
    section: "File Tree Settings",
    label: "Hidden File Patterns",
    description: "Files matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "files", "patterns", "glob", "filter", "exclude"],
  },
  {
    id: "file-tree-hidden-directory-patterns",
    tab: "fileTree",
    section: "File Tree Settings",
    label: "Hidden Directory Patterns",
    description: "Directories matching these glob patterns will be hidden from the file tree",
    keywords: ["hidden", "directories", "folders", "patterns", "glob", "filter", "exclude"],
  },

  // Theme Settings
  {
    id: "theme-theme",
    tab: "theme",
    section: "Appearance",
    label: "Theme",
    description: "Choose your preferred color theme",
    keywords: ["theme", "color", "appearance", "dark", "light"],
  },
  {
    id: "theme-native-menu-bar",
    tab: "theme",
    section: "Appearance",
    label: "Native Menu Bar",
    description: "Use the native menu bar or a custom UI menu bar",
    keywords: ["menu", "bar", "native", "ui"],
  },
  {
    id: "theme-compact-menu-bar",
    tab: "theme",
    section: "Appearance",
    label: "Compact Menu Bar",
    description: "Requires UI menu bar; compact hamburger or full UI menu",
    keywords: ["menu", "bar", "compact", "hamburger", "ui"],
  },

  // AI Settings
  {
    id: "ai-provider",
    tab: "ai",
    section: "Provider & Model",
    label: "Provider",
    description: "Choose your AI service provider",
    keywords: ["ai", "provider", "llm", "service"],
  },
  {
    id: "ai-model",
    tab: "ai",
    section: "Provider & Model",
    label: "Model",
    description: "Select the AI model to use",
    keywords: ["ai", "model", "llm"],
  },
  {
    id: "ai-api-keys",
    tab: "ai",
    section: "API Keys",
    label: "API Keys",
    description: "Configure API keys for AI providers",
    keywords: ["api", "key", "authentication", "credentials"],
  },

  // Keyboard Settings
  {
    id: "keyboard-quick-file-open",
    tab: "keyboard",
    section: "File Operations",
    label: "Quick File Open",
    description: "Open file picker",
    keywords: ["keyboard", "shortcut", "file", "open", "picker"],
  },
  {
    id: "keyboard-save-file",
    tab: "keyboard",
    section: "File Operations",
    label: "Save File",
    description: "Save current file",
    keywords: ["keyboard", "shortcut", "save", "file"],
  },
  {
    id: "keyboard-new-file",
    tab: "keyboard",
    section: "File Operations",
    label: "New File",
    description: "Create new file",
    keywords: ["keyboard", "shortcut", "new", "file", "create"],
  },
  {
    id: "keyboard-close-tab",
    tab: "keyboard",
    section: "File Operations",
    label: "Close Tab",
    description: "Close current tab",
    keywords: ["keyboard", "shortcut", "close", "tab"],
  },
  {
    id: "keyboard-command-palette",
    tab: "keyboard",
    section: "Navigation",
    label: "Command Palette",
    description: "Open command palette",
    keywords: ["keyboard", "shortcut", "command", "palette"],
  },
  {
    id: "keyboard-toggle-sidebar",
    tab: "keyboard",
    section: "Navigation",
    label: "Toggle Sidebar",
    description: "Show/hide sidebar",
    keywords: ["keyboard", "shortcut", "sidebar", "toggle"],
  },
  {
    id: "keyboard-go-to-line",
    tab: "keyboard",
    section: "Navigation",
    label: "Go to Line",
    description: "Jump to specific line",
    keywords: ["keyboard", "shortcut", "go", "line", "jump", "navigate"],
  },
  {
    id: "keyboard-next-tab",
    tab: "keyboard",
    section: "Navigation",
    label: "Next Tab",
    description: "Switch to next tab",
    keywords: ["keyboard", "shortcut", "tab", "next", "switch"],
  },
  {
    id: "keyboard-find",
    tab: "keyboard",
    section: "Editor",
    label: "Find",
    description: "Search in current file",
    keywords: ["keyboard", "shortcut", "find", "search"],
  },
  {
    id: "keyboard-find-replace",
    tab: "keyboard",
    section: "Editor",
    label: "Find & Replace",
    description: "Find and replace text",
    keywords: ["keyboard", "shortcut", "find", "replace", "search"],
  },
  {
    id: "keyboard-comment-line",
    tab: "keyboard",
    section: "Editor",
    label: "Comment Line",
    description: "Toggle line comment",
    keywords: ["keyboard", "shortcut", "comment", "toggle"],
  },
  {
    id: "keyboard-duplicate-line",
    tab: "keyboard",
    section: "Editor",
    label: "Duplicate Line",
    description: "Duplicate current line",
    keywords: ["keyboard", "shortcut", "duplicate", "line", "copy"],
  },
  {
    id: "keyboard-toggle-terminal",
    tab: "keyboard",
    section: "Terminal",
    label: "Toggle Terminal",
    description: "Show/hide integrated terminal",
    keywords: ["keyboard", "shortcut", "terminal", "toggle"],
  },
  {
    id: "keyboard-new-terminal",
    tab: "keyboard",
    section: "Terminal",
    label: "New Terminal",
    description: "Create new terminal instance",
    keywords: ["keyboard", "shortcut", "terminal", "new", "create"],
  },

  // Language Settings
  {
    id: "language-default-language",
    tab: "language",
    section: "Language Support",
    label: "Default Language",
    description: "Default syntax highlighting for new files",
    keywords: ["language", "syntax", "highlighting", "default"],
  },
  {
    id: "language-auto-detect",
    tab: "language",
    section: "Language Support",
    label: "Auto-detect Language",
    description: "Automatically detect file language from extension",
    keywords: ["language", "auto", "detect", "extension"],
  },
  {
    id: "language-format-on-save",
    tab: "language",
    section: "Code Formatting",
    label: "Format on Save",
    description: "Automatically format code when saving",
    keywords: ["format", "save", "automatic", "formatting", "prettier"],
  },
  {
    id: "language-formatter",
    tab: "language",
    section: "Code Formatting",
    label: "Default Formatter",
    description: "Choose default code formatter",
    keywords: ["format", "formatter", "prettier", "eslint"],
  },
  {
    id: "language-auto-completion",
    tab: "language",
    section: "IntelliSense",
    label: "Auto Completion",
    description: "Show completion suggestions while typing",
    keywords: ["autocomplete", "completion", "intellisense", "suggestions"],
  },
  {
    id: "language-parameter-hints",
    tab: "language",
    section: "IntelliSense",
    label: "Parameter Hints",
    description: "Show function parameter hints",
    keywords: ["parameter", "hints", "intellisense", "function"],
  },

  // Features Settings
  {
    id: "features-git",
    tab: "features",
    section: "Features",
    label: "Git Integration",
    description: "Source control management with Git repositories",
    keywords: ["git", "source", "control", "version"],
  },
  {
    id: "features-remote",
    tab: "features",
    section: "Features",
    label: "Remote Development",
    description: "Connect to remote servers via SSH",
    keywords: ["remote", "ssh", "server", "development"],
  },
  {
    id: "features-terminal",
    tab: "features",
    section: "Features",
    label: "Integrated Terminal",
    description: "Built-in terminal for command line operations",
    keywords: ["terminal", "command", "line", "shell"],
  },
  {
    id: "features-search",
    tab: "features",
    section: "Features",
    label: "Global Search",
    description: "Search across files and folders in workspace",
    keywords: ["search", "find", "global", "workspace"],
  },
  {
    id: "features-diagnostics",
    tab: "features",
    section: "Features",
    label: "Diagnostics & Problems",
    description: "Code diagnostics and error reporting",
    keywords: ["diagnostics", "problems", "errors", "linting"],
  },
  {
    id: "features-ai-chat",
    tab: "features",
    section: "Features",
    label: "AI Assistant",
    description: "AI-powered code assistance and chat",
    keywords: ["ai", "assistant", "chat", "copilot"],
  },
  {
    id: "features-breadcrumbs",
    tab: "features",
    section: "Features",
    label: "Breadcrumbs",
    description: "File path navigation breadcrumbs in editor",
    keywords: ["breadcrumbs", "navigation", "path"],
  },

  // Advanced Settings
  {
    id: "advanced-file-watcher",
    tab: "advanced",
    section: "Performance",
    label: "File Watcher",
    description: "Watch for file changes in workspace",
    keywords: ["file", "watcher", "watch", "changes", "performance"],
  },
  {
    id: "advanced-memory-limit",
    tab: "advanced",
    section: "Performance",
    label: "Memory Limit",
    description: "Maximum memory usage (MB)",
    keywords: ["memory", "limit", "performance", "usage"],
  },
  {
    id: "advanced-developer-mode",
    tab: "advanced",
    section: "Development",
    label: "Developer Mode",
    description: "Enable developer tools and debug features",
    keywords: ["developer", "mode", "debug", "tools"],
  },
  {
    id: "advanced-debug-logging",
    tab: "advanced",
    section: "Development",
    label: "Debug Logging",
    description: "Show detailed logs in console",
    keywords: ["debug", "logging", "logs", "console"],
  },
  {
    id: "advanced-auto-update-extensions",
    tab: "advanced",
    section: "Extensions",
    label: "Auto Update Extensions",
    description: "Automatically update installed extensions",
    keywords: ["extensions", "auto", "update", "automatic"],
  },
  {
    id: "advanced-extension-host",
    tab: "advanced",
    section: "Extensions",
    label: "Extension Host",
    description: "Enable extension host for third-party extensions",
    keywords: ["extensions", "host", "third-party"],
  },
  {
    id: "advanced-clear-cache",
    tab: "advanced",
    section: "Data",
    label: "Clear Cache",
    description: "Clear application cache and temporary files",
    keywords: ["cache", "clear", "temporary", "files"],
  },
  {
    id: "advanced-reset-settings",
    tab: "advanced",
    section: "Data",
    label: "Reset Settings",
    description: "Reset all settings to defaults",
    keywords: ["reset", "settings", "defaults", "restore"],
  },
];
