export const DEFAULT_UI_FONT_FAMILY = "Geist Sans";
export const DEFAULT_MONO_FONT_FAMILY = "Geist Mono";

export const DEFAULT_CODE_FONT_SIZE = 14;
export const DEFAULT_UI_FONT_SIZE_OFFSET = 1;
export const DEFAULT_UI_FONT_SIZE = DEFAULT_CODE_FONT_SIZE + DEFAULT_UI_FONT_SIZE_OFFSET;
export const DEFAULT_TERMINAL_FONT_SIZE = DEFAULT_CODE_FONT_SIZE;
