import { settingsTabCommandIds } from "@/features/keymaps/commands/settings-commands";

/** Palette entries that are not registered commands: query results and other registries. */
export type CommandPaletteProviderId = "settings-search" | "extension-commands" | "vim-commands";

export type CommandPaletteSlot = string | { provider: CommandPaletteProviderId };

/**
 * Display order of the command palette's "All commands" list. Command ids refer to registered
 * commands that declare `palette`; a palette command missing here is listed after these slots.
 */
export const commandPaletteOrder: CommandPaletteSlot[] = [
  "markdown.togglePreview",

  "workbench.toggleSidebar",
  "workbench.toggleBottomPane",
  "view.toggleTerminal",
  "workbench.toggleDiagnostics",
  "workbench.showFind",
  "view.toggleNativeMenuBar",
  "view.toggleCompactMenuBar",
  "workbench.zoomIn",
  "workbench.zoomOut",
  "workbench.zoomReset",
  "browser.newTab",
  "browser.openUrl",
  "terminal.new",
  "terminal.generateName",
  "terminal.find",
  "terminal.previousCommand",
  "terminal.nextCommand",
  "terminal.clear",
  "terminal.selectAll",
  "terminal.copyLastCommandOutput",
  "terminal.split",
  "terminal.splitDown",
  "terminal.unsplit",
  "terminal.focusNextPane",
  "terminal.focusPreviousPane",
  "terminal.zoomIn",
  "terminal.zoomOut",
  "terminal.resetZoom",

  "workbench.openSettings",
  "help.sendProductFeedback",
  "help.showWhatsNew",
  "help.openOnboarding",
  "preferences.openSettingsJson",
  "preferences.colorTheme",
  "preferences.iconTheme",
  "settings.toggleVimMode",
  "editor.toggleWordWrap",
  "editor.toggleLineNumbers",
  "settings.toggleRelativeLineNumbers",
  "settings.toggleAutoSave",
  "settings.toggleAutoDetectLanguage",
  "settings.toggleFormatOnSave",
  "settings.toggleAutoCompletion",
  "settings.toggleParameterHints",
  "settings.toggleInlayHints",
  "settings.toggleCodeLens",
  "settings.toggleSemanticTokens",
  "settings.toggleAiCompletion",
  "workbench.toggleMinimap",
  "settings.toggleTelemetry",
  "features.toggleBreadcrumbs",
  "features.toggleDiagnostics",
  "features.toggleDebugger",
  "features.toggleSearch",
  "features.toggleGit",
  "features.toggleTerminal",
  "features.toggleAgentSessions",
  "features.toggleRemote",
  "features.togglePersistentCommands",
  ...settingsTabCommandIds,
  { provider: "settings-search" },

  "view.showFiles",
  "view.showGit",
  "view.showPullRequests",
  "view.showViews",
  "view.showRunAndDebug",
  "view.showOutline",
  "workbench.showGlobalSearch",
  "view.showIntegrations",
  "file.quickOpen",
  "go.symbolInEditor",

  "workbench.toggleActivePaneFullscreen",
  "workbench.splitEditorRight",
  "workbench.splitEditorDown",
  "workbench.closeEditorGroup",
  "workbench.closeOtherEditorGroups",
  "workbench.moveEditorToNextGroup",
  "workbench.moveEditorToPreviousGroup",
  "workbench.resetEditorGroupSizes",
  "workbench.toggleEditorGroupLock",

  "workspace.manage",
  "share.buffer",
  "share.selection",
  "share.agent",
  "file.new",
  "file.newDocument",
  "file.open",
  "file.openFolder",
  "file.save",
  "file.saveAll",
  "file.saveAs",
  "file.localHistory",
  "file.close",
  "workbench.nextTab",
  "workbench.previousTab",
  "file.reopenClosed",

  { provider: "extension-commands" },

  "window.newTerminalWindow",
  "window.newSettingsWindow",
  "window.newExtensionsWindow",
  "window.minimize",
  "window.toggleMaximize",
  "window.toggleFullscreen",

  "git.openBranchManager",
  "git.checkoutBranch",
  "git.manageWorktrees",
  "git.createBranch",
  "git.deleteBranch",
  "git.showBranchDiff",
  "git.selectRepository",
  "git.initializeRepository",
  "git.showChanges",
  "git.showHistory",
  "git.manageRemotes",
  "git.addRemote",
  "git.removeRemote",
  "git.manageTags",
  "git.createTag",
  "git.deleteTag",
  "git.compareTags",
  "git.viewStashes",
  "git.applyStash",
  "git.popStash",
  "git.dropStash",
  "git.stageAll",
  "git.unstageAll",
  "git.commit",
  "git.push",
  "git.pull",
  "git.fetch",
  "git.discardAll",
  "git.refresh",

  "github.showReleases",
  "github.showDeployments",
  "github.newRelease",
  "github.newIssue",
  "github.newPullRequest",
  "github.runWorkflow",
  "github.showPullRequests",
  "github.showIssues",
  "github.showActions",
  "github.refresh",
  "github.checkAuthentication",
  "github.connectAccount",

  "database.connect",

  "ai.openAgentInNewWindow",
  "ai.toggleFollowAgent",
  "ai.cycleAgentMode",
  "ai.reviewPendingAgentChanges",
  "ai.keepAllAgentChanges",
  "ai.rejectAllAgentChanges",
  "ai.keepAgentHunk",
  "ai.rejectAgentHunk",
  "workbench.agentLauncher",
  "editor.addSelectionToChat",
  "editor.addSelectionToNewChat",
  "ai.openContinuousAgents",
  "ai.manageAllowedCommands",
  "ai.openAcpInspector",
  "ai.importAgentSession",
  "ai.openAgentCliInTerminal",
  "ai.logOutOfAgent",
  "lsp.showStatus",
  "developer.openAthasLog",
  "lsp.restartAllServers",
  "lsp.stopAllServers",
  "cli.installTerminalCommand",
  { provider: "vim-commands" },
  "vim.enterNormalMode",
  "vim.enterInsertMode",
  "vim.enterVisualMode",
];
