import { LanguageDescription } from "@codemirror/language";
import { LANGUAGE_LOADERS } from "./languages";

/** A fenced code block language: its display name, the Athas language id, and the info strings. */
const CODE_BLOCK_LANGUAGES: Array<[name: string, id: string, aliases: string[]]> = [
  ["JavaScript", "javascriptreact", ["js", "jsx", "javascript", "mjs", "cjs", "node"]],
  ["TypeScript", "typescriptreact", ["ts", "tsx", "typescript", "mts", "cts"]],
  ["Python", "python", ["py", "python", "python3", "ipython"]],
  ["Rust", "rust", ["rs", "rust"]],
  ["JSON", "json", ["json", "jsonc", "json5"]],
  ["HTML", "html", ["html", "htm", "xhtml"]],
  ["CSS", "css", ["css"]],
  ["SCSS", "scss", ["scss"]],
  ["Sass", "sass", ["sass"]],
  ["Less", "less", ["less"]],
  ["Go", "go", ["go", "golang"]],
  ["YAML", "yaml", ["yaml", "yml"]],
  ["SQL", "sql", ["sql", "psql", "mysql", "sqlite", "postgres", "postgresql"]],
  ["C", "c", ["c", "h"]],
  ["C++", "cpp", ["cpp", "c++", "cc", "cxx", "hpp"]],
  ["Java", "java", ["java"]],
  ["PHP", "php", ["php"]],
  ["XML", "xml", ["xml", "svg", "plist", "xsl"]],
  ["Vue", "vue", ["vue"]],
  ["Svelte", "svelte", ["svelte"]],
  ["Astro", "astro", ["astro"]],
  ["Angular", "angular", ["angular"]],
  ["Markdown", "markdown", ["md", "markdown", "mdx"]],
  ["Shell", "bash", ["sh", "bash", "zsh", "shell", "shellscript", "console", "fish"]],
  ["Dotenv", "dotenv", ["env", "dotenv"]],
  ["Dockerfile", "dockerfile", ["dockerfile", "docker", "containerfile"]],
  ["Ruby", "ruby", ["rb", "ruby"]],
  ["ERB", "embedded_template", ["erb", "html+erb"]],
  ["Lua", "lua", ["lua"]],
  ["Swift", "swift", ["swift"]],
  ["Kotlin", "kotlin", ["kt", "kts", "kotlin"]],
  ["Scala", "scala", ["scala", "sc"]],
  ["C#", "csharp", ["cs", "csharp", "c#"]],
  ["Objective-C", "objc", ["objc", "objective-c", "objectivec", "m"]],
  ["Dart", "dart", ["dart"]],
  ["TOML", "toml", ["toml"]],
  ["Diff", "diff", ["diff", "patch"]],
  ["R", "r", ["r"]],
  ["Elm", "elm", ["elm"]],
  ["Scheme", "scheme", ["scm", "scheme"]],
  ["Emacs Lisp", "elisp", ["el", "elisp", "emacs-lisp"]],
  ["Common Lisp", "lisp", ["lisp", "cl", "commonlisp"]],
  ["Clojure", "clojure", ["clj", "cljs", "cljc", "clojure", "edn"]],
  ["OCaml", "ocaml", ["ml", "mli", "ocaml"]],
  ["F#", "fsharp", ["fs", "fsx", "fsharp", "f#"]],
  ["Haskell", "haskell", ["hs", "haskell"]],
  ["Erlang", "erlang", ["erl", "erlang"]],
  ["Julia", "julia", ["jl", "julia"]],
  ["Perl", "perl", ["pl", "perl"]],
  ["Groovy", "groovy", ["groovy", "gradle"]],
  ["Nginx", "nginx", ["nginx", "nginxconf"]],
  ["PowerShell", "powershell", ["ps1", "powershell", "pwsh"]],
  ["Batch", "batch", ["bat", "cmd", "batch"]],
  ["CMake", "cmake", ["cmake"]],
  ["Makefile", "makefile", ["make", "makefile", "mk"]],
  ["LaTeX", "latex", ["tex", "latex"]],
  ["Verilog", "verilog", ["v", "verilog", "sv", "systemverilog"]],
  ["Protocol Buffers", "protobuf", ["proto", "protobuf"]],
  ["INI", "ini", ["ini", "cfg", "conf", "properties"]],
  ["Git Ignore", "gitignore", ["gitignore", "ignore"]],
  ["Git Attributes", "gitattributes", ["gitattributes"]],
  ["Vim Script", "vim", ["vim", "viml", "vimscript"]],
  ["reStructuredText", "restructuredtext", ["rst", "restructuredtext"]],
  ["Zig", "zig", ["zig"]],
  ["Nix", "nix", ["nix"]],
  ["Elixir", "elixir", ["ex", "exs", "elixir", "heex"]],
  ["GraphQL", "graphql", ["graphql", "gql"]],
  ["Terraform", "terraform", ["tf", "tfvars", "hcl", "terraform"]],
  ["Solidity", "solidity", ["sol", "solidity"]],
];

/** Languages for fenced code blocks in Markdown, loaded only when a block uses them. */
export const languages = CODE_BLOCK_LANGUAGES.map(([name, id, alias]) =>
  LanguageDescription.of({ name, alias, load: LANGUAGE_LOADERS[id] }),
);
