import type { ExtensionManifest } from "@/extensions/types/extension-manifest";

export const vercelThemeManifest: ExtensionManifest = {
  id: "athas.theme.vercel",
  name: "vercel",
  displayName: "Vercel Theme",
  description: "Light and dark themes inspired by Vercel's dashboard and documentation.",
  version: "1.0.0",
  publisher: "Athas",
  categories: ["Theme"],
  activationEvents: ["onTheme:vercel-light", "onTheme:vercel-dark"],
  license: "MIT",
  installation: {
    type: "bundled",
  },
  themes: [
    {
      id: "vercel-light",
      name: "Vercel Light",
      description: "A minimal light theme with Vercel-inspired accent and syntax colors.",
      appearance: "light",
      colors: {
        "primary-bg": "#ffffff",
        "secondary-bg": "#fafafa",
        text: "#171717",
        "text-light": "#525252",
        "text-lighter": "#737373",
        border: "#e5e5e5",
        hover: "#f5f5f5",
        selected: "#eeeeee",
        accent: "#0070f3",
        error: "#e5484d",
        warning: "#ad5700",
        success: "#007f5f",
        info: "#0070f3",
        cursor: "#171717",
        "line-highlight": "#fafafa",
        "selection-bg": "#eaeaea",
        "git-added": "#007f5f",
        "git-modified": "#ad5700",
        "git-deleted": "#e5484d",
      },
      syntax: {
        keyword: "#d4006a",
        string: "#007f5f",
        number: "#ad5700",
        comment: "#737373",
        variable: "#171717",
        function: "#0070f3",
        constant: "#7928ca",
        property: "#006f62",
        type: "#0070f3",
        operator: "#d4006a",
        punctuation: "#525252",
        boolean: "#ad5700",
        null: "#ad5700",
        regex: "#007f5f",
        tag: "#d4006a",
        attribute: "#7928ca",
      },
    },
    {
      id: "vercel-dark",
      name: "Vercel Dark",
      description: "A minimal black theme with Vercel-inspired accent and syntax colors.",
      appearance: "dark",
      colors: {
        "primary-bg": "#000000",
        "secondary-bg": "#0a0a0a",
        text: "#ededed",
        "text-light": "#a1a1a1",
        "text-lighter": "#737373",
        border: "#262626",
        hover: "#111111",
        selected: "#1a1a1a",
        accent: "#0070f3",
        error: "#ff4d4f",
        warning: "#f5a623",
        success: "#50e3c2",
        info: "#0070f3",
        cursor: "#ededed",
        "line-highlight": "#0a0a0a",
        "selection-bg": "#1a1a1a",
        "git-added": "#50e3c2",
        "git-modified": "#f5a623",
        "git-deleted": "#ff4d4f",
      },
      syntax: {
        keyword: "#ff0080",
        string: "#50e3c2",
        number: "#f5a623",
        comment: "#666666",
        variable: "#ededed",
        function: "#0070f3",
        constant: "#7928ca",
        property: "#79ffe1",
        type: "#0070f3",
        operator: "#ff0080",
        punctuation: "#a1a1a1",
        boolean: "#f5a623",
        null: "#f5a623",
        regex: "#50e3c2",
        tag: "#ff0080",
        attribute: "#7928ca",
      },
    },
  ],
};
