[[themes]]
id = "dracula"
name = "Dracula"
description = "Official Dracula theme with rich purples and vibrant accents"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#282a36"
"--tw-secondary-bg" = "#44475a"
"--tw-text" = "#f8f8f2"
"--tw-text-light" = "#f8f8f2"
"--tw-text-lighter" = "#6272a4"
"--tw-border" = "#44475a"
"--tw-hover" = "#44475a"
"--tw-selected" = "#6272a4"
"--tw-accent" = "#bd93f9"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#ff79c6"
"--tw-syntax-string" = "#f1fa8c"
"--tw-syntax-number" = "#bd93f9"
"--tw-syntax-comment" = "#6272a4"
"--tw-syntax-variable" = "#f8f8f2"
"--tw-syntax-function" = "#50fa7b"
"--tw-syntax-constant" = "#bd93f9"
"--tw-syntax-property" = "#f8f8f2"
"--tw-syntax-type" = "#8be9fd"
"--tw-syntax-operator" = "#ff79c6"
"--tw-syntax-punctuation" = "#f8f8f2"
"--tw-syntax-boolean" = "#bd93f9"
"--tw-syntax-null" = "#bd93f9"
"--tw-syntax-regex" = "#f1fa8c"
"--tw-syntax-jsx" = "#ff79c6"
"--tw-syntax-jsx-attribute" = "#50fa7b"

[[themes]]
id = "dracula-soft"
name = "Dracula Soft"
description = "Softer variant with reduced contrast"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#21222c"
"--tw-secondary-bg" = "#282a36"
"--tw-text" = "#f8f8f2"
"--tw-text-light" = "#e9e9e9"
"--tw-text-lighter" = "#6272a4"
"--tw-border" = "#44475a"
"--tw-hover" = "#3a3c4e"
"--tw-selected" = "#4d5066"
"--tw-accent" = "#bd93f9"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#ff79c6"
"--tw-syntax-string" = "#f1fa8c"
"--tw-syntax-number" = "#bd93f9"
"--tw-syntax-comment" = "#6272a4"
"--tw-syntax-variable" = "#f8f8f2"
"--tw-syntax-function" = "#50fa7b"
"--tw-syntax-constant" = "#bd93f9"
"--tw-syntax-property" = "#f8f8f2"
"--tw-syntax-type" = "#8be9fd"
"--tw-syntax-operator" = "#ff79c6"
"--tw-syntax-punctuation" = "#f8f8f2"
"--tw-syntax-boolean" = "#bd93f9"
"--tw-syntax-null" = "#bd93f9"
"--tw-syntax-regex" = "#f1fa8c"
"--tw-syntax-jsx" = "#ff79c6"
"--tw-syntax-jsx-attribute" = "#50fa7b"