[[themes]]
id = "github-light"
name = "GitHub Light"
description = "Clean light theme inspired by GitHub"
category = "Light"
is_dark = false

[themes.css_variables]
"--tw-primary-bg" = "#ffffff"
"--tw-secondary-bg" = "#f6f8fa"
"--tw-text" = "#24292f"
"--tw-text-light" = "#656d76"
"--tw-text-lighter" = "#8c959f"
"--tw-border" = "#d0d7de"
"--tw-hover" = "#f3f4f6"
"--tw-selected" = "#eaeef2"
"--tw-accent" = "#0969da"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#cf222e"
"--tw-syntax-string" = "#0a3069"
"--tw-syntax-number" = "#0550ae"
"--tw-syntax-comment" = "#6e7781"
"--tw-syntax-variable" = "#953800"
"--tw-syntax-function" = "#8250df"
"--tw-syntax-constant" = "#0550ae"
"--tw-syntax-property" = "#953800"
"--tw-syntax-type" = "#8250df"
"--tw-syntax-operator" = "#cf222e"
"--tw-syntax-punctuation" = "#24292f"
"--tw-syntax-boolean" = "#0550ae"
"--tw-syntax-null" = "#0550ae"
"--tw-syntax-regex" = "#0a3069"
"--tw-syntax-jsx" = "#22863a"
"--tw-syntax-jsx-attribute" = "#8250df"

[[themes]]
id = "github-dark"
name = "GitHub Dark"
description = "Dark theme inspired by GitHub Dark"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#0d1117"
"--tw-secondary-bg" = "#161b22"
"--tw-text" = "#e6edf3"
"--tw-text-light" = "#7d8590"
"--tw-text-lighter" = "#656d76"
"--tw-border" = "#30363d"
"--tw-hover" = "#21262d"
"--tw-selected" = "#30363d"
"--tw-accent" = "#2f81f7"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#ff7b72"
"--tw-syntax-string" = "#a5d6ff"
"--tw-syntax-number" = "#79c0ff"
"--tw-syntax-comment" = "#8b949e"
"--tw-syntax-variable" = "#ffa657"
"--tw-syntax-function" = "#d2a8ff"
"--tw-syntax-constant" = "#79c0ff"
"--tw-syntax-property" = "#ffa657"
"--tw-syntax-type" = "#4ec9b0"
"--tw-syntax-operator" = "#ff7b72"
"--tw-syntax-punctuation" = "#e6edf3"
"--tw-syntax-boolean" = "#79c0ff"
"--tw-syntax-null" = "#79c0ff"
"--tw-syntax-regex" = "#a5d6ff"
"--tw-syntax-jsx" = "#7ee787"
"--tw-syntax-jsx-attribute" = "#d2a8ff"

[[themes]]
id = "github-dark-dimmed"
name = "GitHub Dark Dimmed"
description = "Dimmed variant for reduced eye strain"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#22272e"
"--tw-secondary-bg" = "#2d333b"
"--tw-text" = "#adbac7"
"--tw-text-light" = "#768390"
"--tw-text-lighter" = "#636e7b"
"--tw-border" = "#444c56"
"--tw-hover" = "#373e47"
"--tw-selected" = "#444c56"
"--tw-accent" = "#539bf5"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#f47067"
"--tw-syntax-string" = "#96d0ff"
"--tw-syntax-number" = "#6cb6ff"
"--tw-syntax-comment" = "#768390"
"--tw-syntax-variable" = "#f69d50"
"--tw-syntax-function" = "#dcbdfb"
"--tw-syntax-constant" = "#6cb6ff"
"--tw-syntax-property" = "#f69d50"
"--tw-syntax-type" = "#dcbdfb"
"--tw-syntax-operator" = "#f47067"
"--tw-syntax-punctuation" = "#adbac7"
"--tw-syntax-boolean" = "#6cb6ff"
"--tw-syntax-null" = "#6cb6ff"
"--tw-syntax-regex" = "#96d0ff"
"--tw-syntax-jsx" = "#8ddb8c"
"--tw-syntax-jsx-attribute" = "#dcbdfb"