[[themes]]
id = "vs-code-light"
name = "VS Code Light"
description = "Light theme inspired by Visual Studio Code"
category = "Light"
is_dark = false

[themes.css_variables]
"--tw-primary-bg" = "#ffffff"
"--tw-secondary-bg" = "#f3f3f3"
"--tw-text" = "#333333"
"--tw-text-light" = "#6a6a6a"
"--tw-text-lighter" = "#999999"
"--tw-border" = "#e5e5e5"
"--tw-hover" = "#f0f0f0"
"--tw-selected" = "#e8e8e8"
"--tw-accent" = "#007acc"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#0000ff"
"--tw-syntax-string" = "#a31515"
"--tw-syntax-number" = "#098658"
"--tw-syntax-comment" = "#008000"
"--tw-syntax-variable" = "#001080"
"--tw-syntax-function" = "#795e26"
"--tw-syntax-constant" = "#0070c1"
"--tw-syntax-property" = "#001080"
"--tw-syntax-type" = "#267f99"
"--tw-syntax-operator" = "#000000"
"--tw-syntax-punctuation" = "#000000"
"--tw-syntax-boolean" = "#0000ff"
"--tw-syntax-null" = "#0000ff"
"--tw-syntax-regex" = "#811f3f"
"--tw-syntax-jsx" = "#800000"
"--tw-syntax-jsx-attribute" = "#ff0000"

[[themes]]
id = "vs-code-dark"
name = "VS Code Dark"
description = "Dark theme inspired by Visual Studio Code"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#1e1e1e"
"--tw-secondary-bg" = "#252526"
"--tw-text" = "#cccccc"
"--tw-text-light" = "#969696"
"--tw-text-lighter" = "#6a6a6a"
"--tw-border" = "#3e3e42"
"--tw-hover" = "#2d2d30"
"--tw-selected" = "#3e3e42"
"--tw-accent" = "#007acc"

[themes.syntax_tokens]
"--tw-syntax-keyword" = "#569cd6"
"--tw-syntax-string" = "#ce9178"
"--tw-syntax-number" = "#b5cea8"
"--tw-syntax-comment" = "#6a9955"
"--tw-syntax-variable" = "#9cdcfe"
"--tw-syntax-function" = "#dcdcaa"
"--tw-syntax-constant" = "#4fc1ff"
"--tw-syntax-property" = "#9cdcfe"
"--tw-syntax-type" = "#4ec9b0"
"--tw-syntax-operator" = "#d4d4d4"
"--tw-syntax-punctuation" = "#d4d4d4"
"--tw-syntax-boolean" = "#569cd6"
"--tw-syntax-null" = "#569cd6"
"--tw-syntax-regex" = "#d16969"
"--tw-syntax-jsx" = "#569cd6"
"--tw-syntax-jsx-attribute" = "#92c5f8"