//! TypeScript bindings for the app commands.
//!
//! `bun run bindings` regenerates `src/bindings/commands.ts` through the ignored
//! `export_typescript_bindings` test, and debug builds refresh the same file in the
//! background at startup. Both paths format the output with `vp fmt` so the file
//! on disk always matches what `bun run bindings:check` expects.

use specta_typescript::Typescript;
use std::path::{Path, PathBuf};

const BINDINGS_HEADER: &str = "// Generated by tauri-specta from the Rust command signatures.\n// \
                               Do not edit by hand; run `bun run bindings` after changing a \
                               command.\nimport type * as Lsp from \
                               \"vscode-languageserver-protocol\";\n";

/// The checked-in bindings file, relative to the repository root.
pub(crate) const BINDINGS_PATH: &str = "src/bindings/commands.ts";

fn repo_root() -> PathBuf {
   Path::new(env!("CARGO_MANIFEST_DIR"))
      .parent()
      .map(Path::to_path_buf)
      .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")))
}

/// The exporter walks the whole command type graph recursively, which needs more
/// stack than a default spawned or test thread has in unoptimized builds.
const EXPORT_STACK_SIZE: usize = 64 * 1024 * 1024;

/// The TypeScript exporter with free-form JSON typed as `unknown`.
///
/// Specta describes `serde_json::Value` as a recursive inline type, and the
/// TypeScript formatter recurses through it without end. Free-form JSON is
/// `unknown` on the frontend anyway, so every use is replaced before export.
struct AppTypescript;

impl tauri_specta::LanguageExt for AppTypescript {
   type Error = specta_typescript::Error;

   fn export(
      self,
      cfg: &tauri_specta::BuilderConfiguration,
      path: &Path,
   ) -> Result<(), Self::Error> {
      let mut cfg = cfg.clone();
      let unknown = <specta_typescript::Unknown as specta::Type>::definition(&mut cfg.types);
      let lookup = cfg.types.clone();
      for command in &mut cfg.commands {
         for (_, arg) in &mut command.args {
            erase_json_values(arg, &lookup, &unknown);
         }
         if let Some(result) = &mut command.result {
            erase_json_values(result, &lookup, &unknown);
         }
      }
      cfg.types.iter_mut(|ndt| {
         if is_json_value(ndt) {
            ndt.ty = None;
         } else if let Some(ty) = &mut ndt.ty {
            erase_json_values(ty, &lookup, &unknown);
         }
      });
      tauri_specta::LanguageExt::export(Typescript::default().header(BINDINGS_HEADER), &cfg, path)
   }
}

fn is_json_value(ndt: &specta::datatype::NamedDataType) -> bool {
   ndt.name == "Value" && ndt.module_path.starts_with("serde_json")
}

fn erase_json_values(
   dt: &mut specta::datatype::DataType,
   types: &specta::Types,
   unknown: &specta::datatype::DataType,
) {
   use specta::datatype::{DataType, Fields, NamedReferenceType, Reference};

   fn fields(fields: &mut Fields, types: &specta::Types, unknown: &DataType) {
      match fields {
         Fields::Unit => {}
         Fields::Unnamed(unnamed) => unnamed
            .fields
            .iter_mut()
            .filter_map(|field| field.ty.as_mut())
            .for_each(|ty| erase_json_values(ty, types, unknown)),
         Fields::Named(named) => named
            .fields
            .iter_mut()
            .filter_map(|(_, field)| field.ty.as_mut())
            .for_each(|ty| erase_json_values(ty, types, unknown)),
      }
   }

   match dt {
      DataType::Primitive(_) | DataType::Generic(_) | DataType::Reference(Reference::Opaque(_)) => {
      }
      DataType::List(list) => erase_json_values(&mut list.ty, types, unknown),
      DataType::Map(map) => {
         erase_json_values(map.key_ty_mut(), types, unknown);
         erase_json_values(map.value_ty_mut(), types, unknown);
      }
      DataType::Nullable(inner) => erase_json_values(inner, types, unknown),
      DataType::Struct(strct) => fields(&mut strct.fields, types, unknown),
      DataType::Enum(enm) => enm
         .variants
         .iter_mut()
         .for_each(|(_, variant)| fields(&mut variant.fields, types, unknown)),
      DataType::Tuple(tuple) => tuple
         .elements
         .iter_mut()
         .for_each(|ty| erase_json_values(ty, types, unknown)),
      DataType::Intersection(parts) => parts
         .iter_mut()
         .for_each(|ty| erase_json_values(ty, types, unknown)),
      DataType::Reference(Reference::Named(reference)) => {
         if types.get(reference).is_some_and(is_json_value) {
            *dt = unknown.clone();
            return;
         }
         match &mut reference.inner {
            NamedReferenceType::Inline { dt, .. } => erase_json_values(dt, types, unknown),
            NamedReferenceType::Reference { generics, .. } => generics
               .iter_mut()
               .for_each(|(_, ty)| erase_json_values(ty, types, unknown)),
            NamedReferenceType::Recursive(_) => {}
         }
      }
   }
}

/// Writes the unformatted bindings for `builder` to `path`.
pub(crate) fn export_raw(
   builder: &tauri_specta::Builder<tauri::Wry>,
   path: &Path,
) -> Result<(), String> {
   if let Some(parent) = path.parent() {
      std::fs::create_dir_all(parent).map_err(|error| error.to_string())?;
   }
   let builder = builder.clone();
   let path = path.to_path_buf();
   std::thread::Builder::new()
      .name("bindings-export".into())
      .stack_size(EXPORT_STACK_SIZE)
      .spawn(move || {
         builder
            .export(AppTypescript, &path)
            .map_err(|error| error.to_string())
      })
      .map_err(|error| error.to_string())?
      .join()
      .map_err(|_| "bindings export panicked".to_string())?
}

fn format_with_vp(root: &Path, source: &str) -> Result<String, String> {
   use std::{
      io::Write,
      process::{Command, Stdio},
   };

   let vp = root
      .join("node_modules")
      .join(".bin")
      .join(if cfg!(windows) { "vp.cmd" } else { "vp" });
   let mut child = Command::new(vp)
      .arg("fmt")
      .arg(format!("--stdin-filepath={BINDINGS_PATH}"))
      .current_dir(root)
      .stdin(Stdio::piped())
      .stdout(Stdio::piped())
      .stderr(Stdio::piped())
      .spawn()
      .map_err(|error| format!("failed to start vp fmt: {error}"))?;
   child
      .stdin
      .take()
      .ok_or_else(|| "vp fmt stdin unavailable".to_string())?
      .write_all(source.as_bytes())
      .map_err(|error| error.to_string())?;
   let output = child
      .wait_with_output()
      .map_err(|error| error.to_string())?;
   if !output.status.success() {
      return Err(String::from_utf8_lossy(&output.stderr).into_owned());
   }
   String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

/// Refreshes `src/bindings/commands.ts` off the main thread in debug builds.
///
/// The file is only rewritten when the formatted output differs, so a dev launch
/// with unchanged commands never touches the working tree or triggers a reload.
pub(crate) fn export_in_background(builder: &tauri_specta::Builder<tauri::Wry>) {
   let builder = builder.clone();
   std::thread::spawn(move || {
      let root = repo_root();
      let target = root.join(BINDINGS_PATH);
      let scratch = std::env::temp_dir().join(format!("athas-bindings-{}.ts", std::process::id()));
      let result = export_raw(&builder, &scratch)
         .and_then(|()| std::fs::read_to_string(&scratch).map_err(|error| error.to_string()))
         .and_then(|raw| format_with_vp(&root, &raw))
         .and_then(|formatted| {
            let current = std::fs::read_to_string(&target).unwrap_or_default();
            if current == formatted {
               return Ok(false);
            }
            std::fs::write(&target, formatted)
               .map(|()| true)
               .map_err(|error| error.to_string())
         });
      let _ = std::fs::remove_file(&scratch);
      match result {
         Ok(true) => log::info!("[bindings] updated {BINDINGS_PATH}"),
         Ok(false) => {}
         Err(error) => log::warn!("[bindings] failed to refresh {BINDINGS_PATH}: {error}"),
      }
   });
}

#[cfg(test)]
mod tests {
   use super::*;

   /// Regenerates the bindings. Run through `bun run bindings`, which formats the
   /// output; `ATHAS_BINDINGS_OUT` overrides the destination.
   #[test]
   #[ignore = "writes bindings; run through `bun run bindings`"]
   fn export_typescript_bindings() {
      let path = std::env::var_os("ATHAS_BINDINGS_OUT")
         .map(PathBuf::from)
         .unwrap_or_else(|| repo_root().join(BINDINGS_PATH));
      export_raw(&crate::specta_builder(), &path).expect("failed to export bindings");
   }

   #[test]
   fn bindings_export_without_errors() {
      let path =
         std::env::temp_dir().join(format!("athas-bindings-test-{}.ts", std::process::id()));
      let result = export_raw(&crate::specta_builder(), &path);
      let _ = std::fs::remove_file(&path);
      result.expect("bindings should export");
   }
}
